#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa a aplicação (-OO)
/usr/bin/env python ./anvsrv.py "$@" > ./anvsrv.$HOST.log 2>&1
