#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa o editor da base de dados
/usr/bin/env python -OO ./dbEdit.py "$@" 2> ./dbEdit.$HOST.log
