#!/bin/sh

INSTALL_DIR=/usr/local/lib/python2.7/dist-packages
PTRACKS=ptracks

echo "Adding ptracks to Python path (/usr/local/lib/python2.7/dist-packages)"
if [ -d $INSTALL_DIR/$PTRACKS ]; then
	service ptracks-net stop
	service core-daemon stop
	rm -f /usr/local/lib/python2.7/dist-packages/ptracks
fi

ln -s `pwd`/ptracks /usr/local/lib/python2.7/dist-packages/ptracks

#
# /etc/ptracks
#
echo "Creating /etc/ptracks directory"
if [ -d /etc/$PTRACKS ]; then
	rm -rf /etc/ptracks
fi
sudo mkdir /etc/ptracks
ln -s `pwd`/data /etc/ptracks/data
ln -s `pwd`/data /usr/local/lib/python2.7/dist-packages/ptracks/data
ln -s `pwd`/tracks.cfg /etc/ptracks/tracks.cfg
ln -s `pwd`/public_html /etc/ptracks/public_html

#
# /etc/init.d/ptracks
#
echo "Creating /etc/init.d/ptracks script"
rm -rf /etc/init.d/ptracks
rm -rf /etc/init.d/ptracks-net
ln -s `pwd`/bin/ptracks-daemon /etc/init.d/ptracks
ln -s `pwd`/bin/ptracks-net /etc/init.d/ptracks-net


#
# System binaries
#
echo "Copying binaries to /usr/local/bin/ptracks"
rm -f /usr/local/bin/ptracks*
sudo cp bin/* /usr/local/bin

service ptracks-net start
service core-daemon start

echo "Installation complete"
