#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa a aplicação
mpiexec -n $1 --hostfile newHosts.$HOST ./newton "${@:2}"
