#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa a aplicação
/usr/bin/env python -OO ./newton.py "$@" 2> ./newton.$HOST.log
