#!/bin/bash

# desabilita o proxy
if [ -e ./x_proxy.sh ]
then
    source ./x_proxy.sh
fi
    
# nome do computador
HOST=`hostname`

# executa o dynamic configuration tool
/usr/bin/env python -OO ./super.py "$@" 2> ./super.$HOST.log
