#!/bin/bash

## -----------------------------------------------------------------------
#  desabilita o proxy
#
source ./x_proxy.sh

## -----------------------------------------------------------------------
#  nome do computador
#
HOST=`hostname`

## -----------------------------------------------------------------------
#  diretório da aplicação
#
# cd ~/Public/wrk.srce/pTrack/atual

## -----------------------------------------------------------------------
#  executa a aplicação
#
# /usr/bin/env python -OO ./visil.py 2> ./visil.$HOST.log
/usr/bin/env python ./visil.py 2> ./visil.$HOST.log

## -----------------------------------------------------------------------
#  diretório raiz
#
# cd ~
