# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_exe_data_new.ui'
#
# Created: Wed Dec  7 12:55:06 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgExeDataNEW(object):
    def setupUi(self, CDlgExeDataNEW):
        CDlgExeDataNEW.setObjectName(_fromUtf8("CDlgExeDataNEW"))
        CDlgExeDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        CDlgExeDataNEW.resize(846, 730)
        CDlgExeDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgExeDataNEW.setSizeGripEnabled(True)
        CDlgExeDataNEW.setModal(True)
        self.horizontalLayout_2 = QtGui.QHBoxLayout(CDlgExeDataNEW)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.splitter = QtGui.QSplitter(CDlgExeDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widExeTab = QtGui.QWidget(self.splitter)
        self.widExeTab.setObjectName(_fromUtf8("widExeTab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widExeTab)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.qtwExeTab = QtGui.QTableWidget(self.widExeTab)
        self.qtwExeTab.setMinimumSize(QtCore.QSize(370, 0))
        self.qtwExeTab.setObjectName(_fromUtf8("qtwExeTab"))
        self.qtwExeTab.setColumnCount(0)
        self.qtwExeTab.setRowCount(0)
        self.verticalLayout_7.addWidget(self.qtwExeTab)
        self.widData = QtGui.QWidget(self.splitter)
        self.widData.setObjectName(_fromUtf8("widData"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widData)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frmExeID = QtGui.QFrame(self.widData)
        self.frmExeID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmExeID.setFrameShadow(QtGui.QFrame.Raised)
        self.frmExeID.setLineWidth(1)
        self.frmExeID.setObjectName(_fromUtf8("frmExeID"))
        self.gridLayout = QtGui.QGridLayout(self.frmExeID)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblExeDesc = QtGui.QLabel(self.frmExeID)
        self.lblExeDesc.setObjectName(_fromUtf8("lblExeDesc"))
        self.gridLayout.addWidget(self.lblExeDesc, 1, 0, 1, 1)
        self.txtExeID = QtGui.QLabel(self.frmExeID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtExeID.setFont(font)
        self.txtExeID.setObjectName(_fromUtf8("txtExeID"))
        self.gridLayout.addWidget(self.txtExeID, 0, 2, 1, 1)
        self.lblExeID = QtGui.QLabel(self.frmExeID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblExeID.sizePolicy().hasHeightForWidth())
        self.lblExeID.setSizePolicy(sizePolicy)
        self.lblExeID.setObjectName(_fromUtf8("lblExeID"))
        self.gridLayout.addWidget(self.lblExeID, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 3, 1, 1)
        self.qleExeDesc = QtGui.QLineEdit(self.frmExeID)
        self.qleExeDesc.setObjectName(_fromUtf8("qleExeDesc"))
        self.gridLayout.addWidget(self.qleExeDesc, 1, 2, 1, 2)
        self.verticalLayout.addWidget(self.frmExeID)
        self.tabExe = QtGui.QTabWidget(self.widData)
        self.tabExe.setObjectName(_fromUtf8("tabExe"))
        self.pagExe = QtGui.QWidget()
        self.pagExe.setObjectName(_fromUtf8("pagExe"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pagExe)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gbxExeSit = QtGui.QGroupBox(self.pagExe)
        self.gbxExeSit.setObjectName(_fromUtf8("gbxExeSit"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gbxExeSit)
        self.horizontalLayout_7.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.widExeSit = QtGui.QWidget(self.gbxExeSit)
        self.widExeSit.setObjectName(_fromUtf8("widExeSit"))
        self.gridLayout_8 = QtGui.QGridLayout(self.widExeSit)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.tedSitHorIni = QtGui.QTimeEdit(self.widExeSit)
        self.tedSitHorIni.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tedSitHorIni.setTime(QtCore.QTime(0, 0, 0))
        self.tedSitHorIni.setTimeSpec(QtCore.Qt.LocalTime)
        self.tedSitHorIni.setObjectName(_fromUtf8("tedSitHorIni"))
        self.gridLayout_8.addWidget(self.tedSitHorIni, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem1, 2, 2, 1, 1)
        self.lblSitHorAtu = QtGui.QLabel(self.widExeSit)
        self.lblSitHorAtu.setObjectName(_fromUtf8("lblSitHorAtu"))
        self.gridLayout_8.addWidget(self.lblSitHorAtu, 2, 0, 1, 1)
        self.lblSitHorIni = QtGui.QLabel(self.widExeSit)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblSitHorIni.sizePolicy().hasHeightForWidth())
        self.lblSitHorIni.setSizePolicy(sizePolicy)
        self.lblSitHorIni.setObjectName(_fromUtf8("lblSitHorIni"))
        self.gridLayout_8.addWidget(self.lblSitHorIni, 1, 0, 1, 1)
        self.lblSitVelExe = QtGui.QLabel(self.widExeSit)
        self.lblSitVelExe.setObjectName(_fromUtf8("lblSitVelExe"))
        self.gridLayout_8.addWidget(self.lblSitVelExe, 2, 3, 1, 1)
        self.cbxSitEstado = QtGui.QCheckBox(self.widExeSit)
        self.cbxSitEstado.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.cbxSitEstado.setChecked(True)
        self.cbxSitEstado.setObjectName(_fromUtf8("cbxSitEstado"))
        self.gridLayout_8.addWidget(self.cbxSitEstado, 1, 5, 1, 1)
        self.tedSitHorAtu = QtGui.QTimeEdit(self.widExeSit)
        self.tedSitHorAtu.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tedSitHorAtu.setTime(QtCore.QTime(0, 0, 0))
        self.tedSitHorAtu.setTimeSpec(QtCore.Qt.LocalTime)
        self.tedSitHorAtu.setObjectName(_fromUtf8("tedSitHorAtu"))
        self.gridLayout_8.addWidget(self.tedSitHorAtu, 2, 1, 1, 1)
        self.dsbSitVelExe = QtGui.QDoubleSpinBox(self.widExeSit)
        self.dsbSitVelExe.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbSitVelExe.setDecimals(1)
        self.dsbSitVelExe.setMinimum(0.1)
        self.dsbSitVelExe.setMaximum(5.0)
        self.dsbSitVelExe.setSingleStep(0.5)
        self.dsbSitVelExe.setProperty("value", 1.0)
        self.dsbSitVelExe.setObjectName(_fromUtf8("dsbSitVelExe"))
        self.gridLayout_8.addWidget(self.dsbSitVelExe, 2, 5, 1, 1)
        self.horizontalLayout_7.addWidget(self.widExeSit)
        self.verticalLayout_4.addWidget(self.gbxExeSit)
        self.gbxExeMet = QtGui.QGroupBox(self.pagExe)
        self.gbxExeMet.setObjectName(_fromUtf8("gbxExeMet"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gbxExeMet)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widAltTrans = QtGui.QWidget(self.gbxExeMet)
        self.widAltTrans.setObjectName(_fromUtf8("widAltTrans"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widAltTrans)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblMetAltTrans = QtGui.QLabel(self.widAltTrans)
        self.lblMetAltTrans.setObjectName(_fromUtf8("lblMetAltTrans"))
        self.horizontalLayout.addWidget(self.lblMetAltTrans)
        self.sbxAltTrans = QtGui.QSpinBox(self.widAltTrans)
        self.sbxAltTrans.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxAltTrans.setMaximum(50000)
        self.sbxAltTrans.setSingleStep(100)
        self.sbxAltTrans.setObjectName(_fromUtf8("sbxAltTrans"))
        self.horizontalLayout.addWidget(self.sbxAltTrans)
        self.verticalLayout_6.addWidget(self.widAltTrans)
        self.gbxMetVnt = QtGui.QGroupBox(self.gbxExeMet)
        self.gbxMetVnt.setObjectName(_fromUtf8("gbxMetVnt"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbxMetVnt)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblVntVer = QtGui.QLabel(self.gbxMetVnt)
        self.lblVntVer.setObjectName(_fromUtf8("lblVntVer"))
        self.gridLayout_4.addWidget(self.lblVntVer, 2, 0, 1, 1)
        self.sbxVentNiv_2 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentNiv_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentNiv_2.setMaximum(400)
        self.sbxVentNiv_2.setSingleStep(10)
        self.sbxVentNiv_2.setObjectName(_fromUtf8("sbxVentNiv_2"))
        self.gridLayout_4.addWidget(self.sbxVentNiv_2, 0, 2, 1, 1)
        self.sbxVentNiv_3 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentNiv_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentNiv_3.setMaximum(400)
        self.sbxVentNiv_3.setSingleStep(10)
        self.sbxVentNiv_3.setObjectName(_fromUtf8("sbxVentNiv_3"))
        self.gridLayout_4.addWidget(self.sbxVentNiv_3, 0, 3, 1, 1)
        self.sbxVentVer_2 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentVer_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentVer_2.setMaximum(300)
        self.sbxVentVer_2.setSingleStep(10)
        self.sbxVentVer_2.setObjectName(_fromUtf8("sbxVentVer_2"))
        self.gridLayout_4.addWidget(self.sbxVentVer_2, 2, 2, 1, 1)
        self.lblVntNiv = QtGui.QLabel(self.gbxMetVnt)
        self.lblVntNiv.setObjectName(_fromUtf8("lblVntNiv"))
        self.gridLayout_4.addWidget(self.lblVntNiv, 0, 0, 1, 1)
        self.lblVntHor = QtGui.QLabel(self.gbxMetVnt)
        self.lblVntHor.setObjectName(_fromUtf8("lblVntHor"))
        self.gridLayout_4.addWidget(self.lblVntHor, 1, 0, 1, 1)
        self.sbxVentNiv_1 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentNiv_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentNiv_1.setMaximum(400)
        self.sbxVentNiv_1.setSingleStep(10)
        self.sbxVentNiv_1.setObjectName(_fromUtf8("sbxVentNiv_1"))
        self.gridLayout_4.addWidget(self.sbxVentNiv_1, 0, 1, 1, 1)
        self.sbxVentHor_1 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentHor_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentHor_1.setMaximum(300)
        self.sbxVentHor_1.setSingleStep(10)
        self.sbxVentHor_1.setObjectName(_fromUtf8("sbxVentHor_1"))
        self.gridLayout_4.addWidget(self.sbxVentHor_1, 1, 1, 1, 1)
        self.sbxVentVer_1 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentVer_1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentVer_1.setMaximum(300)
        self.sbxVentVer_1.setSingleStep(10)
        self.sbxVentVer_1.setObjectName(_fromUtf8("sbxVentVer_1"))
        self.gridLayout_4.addWidget(self.sbxVentVer_1, 2, 1, 1, 1)
        self.sbxVentHor_2 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentHor_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentHor_2.setMaximum(300)
        self.sbxVentHor_2.setSingleStep(10)
        self.sbxVentHor_2.setObjectName(_fromUtf8("sbxVentHor_2"))
        self.gridLayout_4.addWidget(self.sbxVentHor_2, 1, 2, 1, 1)
        self.sbxVentVer_3 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentVer_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentVer_3.setMaximum(300)
        self.sbxVentVer_3.setSingleStep(10)
        self.sbxVentVer_3.setObjectName(_fromUtf8("sbxVentVer_3"))
        self.gridLayout_4.addWidget(self.sbxVentVer_3, 2, 3, 1, 1)
        self.sbxVentHor_3 = QtGui.QSpinBox(self.gbxMetVnt)
        self.sbxVentHor_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxVentHor_3.setMaximum(300)
        self.sbxVentHor_3.setSingleStep(10)
        self.sbxVentHor_3.setObjectName(_fromUtf8("sbxVentHor_3"))
        self.gridLayout_4.addWidget(self.sbxVentHor_3, 1, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.gbxMetVnt)
        self.gbxMetQNH = QtGui.QGroupBox(self.gbxExeMet)
        self.gbxMetQNH.setObjectName(_fromUtf8("gbxMetQNH"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbxMetQNH)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblQNHSup = QtGui.QLabel(self.gbxMetQNH)
        self.lblQNHSup.setObjectName(_fromUtf8("lblQNHSup"))
        self.gridLayout_3.addWidget(self.lblQNHSup, 1, 2, 1, 1)
        self.sbxQNHSup = QtGui.QSpinBox(self.gbxMetQNH)
        self.sbxQNHSup.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxQNHSup.setObjectName(_fromUtf8("sbxQNHSup"))
        self.gridLayout_3.addWidget(self.sbxQNHSup, 1, 3, 1, 1)
        self.lblQNH = QtGui.QLabel(self.gbxMetQNH)
        self.lblQNH.setObjectName(_fromUtf8("lblQNH"))
        self.gridLayout_3.addWidget(self.lblQNH, 0, 0, 1, 1)
        self.sbxQNH = QtGui.QSpinBox(self.gbxMetQNH)
        self.sbxQNH.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxQNH.setObjectName(_fromUtf8("sbxQNH"))
        self.gridLayout_3.addWidget(self.sbxQNH, 0, 1, 1, 1)
        self.lblQNHInf = QtGui.QLabel(self.gbxMetQNH)
        self.lblQNHInf.setObjectName(_fromUtf8("lblQNHInf"))
        self.gridLayout_3.addWidget(self.lblQNHInf, 0, 2, 1, 1)
        self.sbxQNHInf = QtGui.QSpinBox(self.gbxMetQNH)
        self.sbxQNHInf.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxQNHInf.setObjectName(_fromUtf8("sbxQNHInf"))
        self.gridLayout_3.addWidget(self.sbxQNHInf, 0, 3, 1, 1)
        self.lblQNHPend = QtGui.QLabel(self.gbxMetQNH)
        self.lblQNHPend.setObjectName(_fromUtf8("lblQNHPend"))
        self.gridLayout_3.addWidget(self.lblQNHPend, 1, 0, 1, 1)
        self.sbxQNHPend = QtGui.QSpinBox(self.gbxMetQNH)
        self.sbxQNHPend.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxQNHPend.setObjectName(_fromUtf8("sbxQNHPend"))
        self.gridLayout_3.addWidget(self.sbxQNHPend, 1, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.gbxMetQNH)
        self.verticalLayout_4.addWidget(self.gbxExeMet)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/execute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabExe.addTab(self.pagExe, icon, _fromUtf8(""))
        self.pagAnv = QtGui.QWidget()
        self.pagAnv.setObjectName(_fromUtf8("pagAnv"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pagAnv)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gbxExeAnv = QtGui.QGroupBox(self.pagAnv)
        self.gbxExeAnv.setObjectName(_fromUtf8("gbxExeAnv"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxExeAnv)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.qtwTabAnv = QtGui.QTableWidget(self.gbxExeAnv)
        self.qtwTabAnv.setObjectName(_fromUtf8("qtwTabAnv"))
        self.qtwTabAnv.setColumnCount(0)
        self.qtwTabAnv.setRowCount(0)
        self.verticalLayout_3.addWidget(self.qtwTabAnv)
        self.verticalLayout_5.addWidget(self.gbxExeAnv)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/view.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabExe.addTab(self.pagAnv, icon1, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabExe)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.frmExeBBX = QtGui.QFrame(self.widData)
        self.frmExeBBX.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmExeBBX.setFrameShadow(QtGui.QFrame.Raised)
        self.frmExeBBX.setObjectName(_fromUtf8("frmExeBBX"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frmExeBBX)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnNew = QtGui.QPushButton(self.frmExeBBX)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon2)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.horizontalLayout_3.addWidget(self.btnNew)
        self.btnDel = QtGui.QPushButton(self.frmExeBBX)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDel.setIcon(icon3)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.horizontalLayout_3.addWidget(self.btnDel)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.bbxExeTab = QtGui.QDialogButtonBox(self.frmExeBBX)
        self.bbxExeTab.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbxExeTab.setObjectName(_fromUtf8("bbxExeTab"))
        self.horizontalLayout_3.addWidget(self.bbxExeTab)
        self.verticalLayout.addWidget(self.frmExeBBX)
        self.horizontalLayout_2.addWidget(self.splitter)

        self.retranslateUi(CDlgExeDataNEW)
        self.tabExe.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(CDlgExeDataNEW)

    def retranslateUi(self, CDlgExeDataNEW):
        CDlgExeDataNEW.setWindowTitle(_translate("CDlgExeDataNEW", "Edição de Exercícios", None))
        self.qtwExeTab.setSortingEnabled(True)
        self.lblExeDesc.setText(_translate("CDlgExeDataNEW", "Descrição:", None))
        self.txtExeID.setText(_translate("CDlgExeDataNEW", "TEST001", None))
        self.lblExeID.setText(_translate("CDlgExeDataNEW", "Indicativo:", None))
        self.gbxExeSit.setTitle(_translate("CDlgExeDataNEW", "Situação", None))
        self.tedSitHorIni.setDisplayFormat(_translate("CDlgExeDataNEW", "h:mm", None))
        self.lblSitHorAtu.setText(_translate("CDlgExeDataNEW", "Hora atual:", None))
        self.lblSitHorIni.setText(_translate("CDlgExeDataNEW", "Hora inicial:", None))
        self.lblSitVelExe.setText(_translate("CDlgExeDataNEW", "Velocidade:", None))
        self.cbxSitEstado.setText(_translate("CDlgExeDataNEW", "Congelado", None))
        self.tedSitHorAtu.setDisplayFormat(_translate("CDlgExeDataNEW", "h:mm", None))
        self.gbxExeMet.setTitle(_translate("CDlgExeDataNEW", "Meteorologia", None))
        self.lblMetAltTrans.setText(_translate("CDlgExeDataNEW", "Altitude de transição:", None))
        self.sbxAltTrans.setSuffix(_translate("CDlgExeDataNEW", " ft", None))
        self.gbxMetVnt.setTitle(_translate("CDlgExeDataNEW", "Vento", None))
        self.lblVntVer.setText(_translate("CDlgExeDataNEW", "Vertical:", None))
        self.sbxVentNiv_2.setSuffix(_translate("CDlgExeDataNEW", " ft", None))
        self.sbxVentNiv_3.setSuffix(_translate("CDlgExeDataNEW", " ft", None))
        self.sbxVentVer_2.setSuffix(_translate("CDlgExeDataNEW", " kt", None))
        self.lblVntNiv.setText(_translate("CDlgExeDataNEW", "Nível:", None))
        self.lblVntHor.setText(_translate("CDlgExeDataNEW", "Horizontal:", None))
        self.sbxVentNiv_1.setSuffix(_translate("CDlgExeDataNEW", " ft", None))
        self.sbxVentHor_1.setSuffix(_translate("CDlgExeDataNEW", " kt", None))
        self.sbxVentVer_1.setSuffix(_translate("CDlgExeDataNEW", " kt", None))
        self.sbxVentHor_2.setSuffix(_translate("CDlgExeDataNEW", " kt", None))
        self.sbxVentVer_3.setSuffix(_translate("CDlgExeDataNEW", " kt", None))
        self.sbxVentHor_3.setSuffix(_translate("CDlgExeDataNEW", " kt", None))
        self.gbxMetQNH.setTitle(_translate("CDlgExeDataNEW", "QNH", None))
        self.lblQNHSup.setText(_translate("CDlgExeDataNEW", "Limite superior:", None))
        self.lblQNH.setText(_translate("CDlgExeDataNEW", "QNH:", None))
        self.lblQNHInf.setText(_translate("CDlgExeDataNEW", "Limite inferior:", None))
        self.lblQNHPend.setText(_translate("CDlgExeDataNEW", "Pendente:", None))
        self.tabExe.setTabText(self.tabExe.indexOf(self.pagExe), _translate("CDlgExeDataNEW", "Exercício", None))
        self.gbxExeAnv.setTitle(_translate("CDlgExeDataNEW", "Aeronaves", None))
        self.qtwTabAnv.setSortingEnabled(True)
        self.tabExe.setTabText(self.tabExe.indexOf(self.pagAnv), _translate("CDlgExeDataNEW", "Aeronaves", None))
        self.btnNew.setText(_translate("CDlgExeDataNEW", "Novo", None))
        self.btnDel.setText(_translate("CDlgExeDataNEW", "Remove", None))

import resources_rc
