# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './wnd_main_piloto.ui'
#
# Created: Tue Dec  6 11:23:23 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wndMainPiloto(object):
    def setupUi(self, wndMainPiloto):
        wndMainPiloto.setObjectName(_fromUtf8("wndMainPiloto"))
        wndMainPiloto.resize(1167, 882)
        wndMainPiloto.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.centralwidget = QtGui.QWidget(wndMainPiloto)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        wndMainPiloto.setCentralWidget(self.centralwidget)
        self.status_bar = QtGui.QStatusBar(wndMainPiloto)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        wndMainPiloto.setStatusBar(self.status_bar)
        self.dck_lista_voos = QtGui.QDockWidget(wndMainPiloto)
        self.dck_lista_voos.setObjectName(_fromUtf8("dck_lista_voos"))
        self.dwc_voos = QtGui.QWidget()
        self.dwc_voos.setObjectName(_fromUtf8("dwc_voos"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dwc_voos)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.wid_head_lst = QtGui.QWidget(self.dwc_voos)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_head_lst.sizePolicy().hasHeightForWidth())
        self.wid_head_lst.setSizePolicy(sizePolicy)
        self.wid_head_lst.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: #729fcf;"))
        self.wid_head_lst.setObjectName(_fromUtf8("wid_head_lst"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.wid_head_lst)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setMargin(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_icon = QtGui.QLabel(self.wid_head_lst)
        self.lbl_icon.setText(_fromUtf8(""))
        self.lbl_icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/compile16.png")))
        self.lbl_icon.setObjectName(_fromUtf8("lbl_icon"))
        self.horizontalLayout.addWidget(self.lbl_icon)
        self.lbl_title = QtGui.QLabel(self.wid_head_lst)
        self.lbl_title.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";"))
        self.lbl_title.setObjectName(_fromUtf8("lbl_title"))
        self.horizontalLayout.addWidget(self.lbl_title)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addWidget(self.wid_head_lst)
        self.qtv_stp = QtGui.QTableView(self.dwc_voos)
        self.qtv_stp.setObjectName(_fromUtf8("qtv_stp"))
        self.verticalLayout_3.addWidget(self.qtv_stp)
        self.gbx_comandos = QtGui.QGroupBox(self.dwc_voos)
        self.gbx_comandos.setEnabled(True)
        self.gbx_comandos.setObjectName(_fromUtf8("gbx_comandos"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gbx_comandos)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frm_btn = QtGui.QFrame(self.gbx_comandos)
        self.frm_btn.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_btn.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_btn.setObjectName(_fromUtf8("frm_btn"))
        self.gridLayout = QtGui.QGridLayout(self.frm_btn)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_cmd_altitude = QtGui.QPushButton(self.frm_btn)
        self.btn_cmd_altitude.setEnabled(True)
        self.btn_cmd_altitude.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);\n"
"color:rgb(255, 255, 0);"))
        self.btn_cmd_altitude.setObjectName(_fromUtf8("btn_cmd_altitude"))
        self.gridLayout.addWidget(self.btn_cmd_altitude, 0, 3, 1, 1)
        self.btn_cancela = QtGui.QPushButton(self.frm_btn)
        self.btn_cancela.setEnabled(True)
        self.btn_cancela.setStyleSheet(_fromUtf8("background-color: rgb(255, 0, 0)"))
        self.btn_cancela.setObjectName(_fromUtf8("btn_cancela"))
        self.gridLayout.addWidget(self.btn_cancela, 8, 3, 1, 1)
        self.btn_cod_spi = QtGui.QPushButton(self.frm_btn)
        self.btn_cod_spi.setEnabled(True)
        self.btn_cod_spi.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255);"))
        self.btn_cod_spi.setObjectName(_fromUtf8("btn_cod_spi"))
        self.gridLayout.addWidget(self.btn_cod_spi, 11, 1, 1, 1)
        self.btn_cmd_velocidade = QtGui.QPushButton(self.frm_btn)
        self.btn_cmd_velocidade.setEnabled(True)
        self.btn_cmd_velocidade.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);\n"
"color:rgb(255, 255, 0);"))
        self.btn_cmd_velocidade.setObjectName(_fromUtf8("btn_cmd_velocidade"))
        self.gridLayout.addWidget(self.btn_cmd_velocidade, 0, 1, 1, 1)
        self.btn_cod_ssr = QtGui.QPushButton(self.frm_btn)
        self.btn_cod_ssr.setEnabled(True)
        self.btn_cod_ssr.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255);"))
        self.btn_cod_ssr.setObjectName(_fromUtf8("btn_cod_ssr"))
        self.gridLayout.addWidget(self.btn_cod_ssr, 11, 0, 1, 1)
        self.btn_cod_emg = QtGui.QPushButton(self.frm_btn)
        self.btn_cod_emg.setEnabled(True)
        self.btn_cod_emg.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"color:rgb(255, 255, 255);"))
        self.btn_cod_emg.setObjectName(_fromUtf8("btn_cod_emg"))
        self.gridLayout.addWidget(self.btn_cod_emg, 11, 3, 1, 1)
        self.btn_cmd_direcao = QtGui.QPushButton(self.frm_btn)
        self.btn_cmd_direcao.setEnabled(True)
        self.btn_cmd_direcao.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 255);\n"
"color:rgb(255, 255, 0);"))
        self.btn_cmd_direcao.setObjectName(_fromUtf8("btn_cmd_direcao"))
        self.gridLayout.addWidget(self.btn_cmd_direcao, 0, 0, 1, 1)
        self.btn_prc_esp = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_esp.setEnabled(True)
        self.btn_prc_esp.setStyleSheet(_fromUtf8("background-color: rgb(255, 255,  0);"))
        self.btn_prc_esp.setObjectName(_fromUtf8("btn_prc_esp"))
        self.gridLayout.addWidget(self.btn_prc_esp, 5, 3, 1, 1)
        self.btn_prc_trj = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_trj.setEnabled(True)
        self.btn_prc_trj.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0);"))
        self.btn_prc_trj.setObjectName(_fromUtf8("btn_prc_trj"))
        self.gridLayout.addWidget(self.btn_prc_trj, 5, 0, 1, 1)
        self.btn_prc_dir_fixo = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_dir_fixo.setEnabled(True)
        self.btn_prc_dir_fixo.setStyleSheet(_fromUtf8("background-color: rgb(255, 255,  0);"))
        self.btn_prc_dir_fixo.setObjectName(_fromUtf8("btn_prc_dir_fixo"))
        self.gridLayout.addWidget(self.btn_prc_dir_fixo, 5, 1, 1, 1)
        self.btn_prc_arr = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_arr.setEnabled(True)
        self.btn_prc_arr.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0)"))
        self.btn_prc_arr.setObjectName(_fromUtf8("btn_prc_arr"))
        self.gridLayout.addWidget(self.btn_prc_arr, 8, 0, 1, 1)
        self.btn_prc_dep = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_dep.setEnabled(True)
        self.btn_prc_dep.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0)"))
        self.btn_prc_dep.setObjectName(_fromUtf8("btn_prc_dep"))
        self.gridLayout.addWidget(self.btn_prc_dep, 8, 1, 1, 1)
        self.btn_prc_apx = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_apx.setEnabled(True)
        self.btn_prc_apx.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0)"))
        self.btn_prc_apx.setObjectName(_fromUtf8("btn_prc_apx"))
        self.gridLayout.addWidget(self.btn_prc_apx, 7, 0, 1, 1)
        self.btn_prc_ape = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_ape.setEnabled(True)
        self.btn_prc_ape.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0)"))
        self.btn_prc_ape.setObjectName(_fromUtf8("btn_prc_ape"))
        self.gridLayout.addWidget(self.btn_prc_ape, 7, 1, 1, 1)
        self.btn_prc_ils = QtGui.QPushButton(self.frm_btn)
        self.btn_prc_ils.setEnabled(True)
        self.btn_prc_ils.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 0)"))
        self.btn_prc_ils.setObjectName(_fromUtf8("btn_prc_ils"))
        self.gridLayout.addWidget(self.btn_prc_ils, 7, 3, 1, 1)
        self.verticalLayout.addWidget(self.frm_btn)
        self.wid_cmd_line = QtGui.QWidget(self.gbx_comandos)
        self.wid_cmd_line.setObjectName(_fromUtf8("wid_cmd_line"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.wid_cmd_line)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_comando = QtGui.QLabel(self.wid_cmd_line)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_comando.sizePolicy().hasHeightForWidth())
        self.lbl_comando.setSizePolicy(sizePolicy)
        self.lbl_comando.setStyleSheet(_fromUtf8("background-color:rgb(0, 0, 0);\n"
"color:rgb(0, 190, 0)"))
        self.lbl_comando.setObjectName(_fromUtf8("lbl_comando"))
        self.horizontalLayout_4.addWidget(self.lbl_comando)
        self.btn_send = QtGui.QPushButton(self.wid_cmd_line)
        self.btn_send.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_send.setIcon(icon)
        self.btn_send.setObjectName(_fromUtf8("btn_send"))
        self.horizontalLayout_4.addWidget(self.btn_send)
        self.verticalLayout.addWidget(self.wid_cmd_line)
        self.qlw_history = QtGui.QListWidget(self.gbx_comandos)
        self.qlw_history.setStyleSheet(_fromUtf8("background-color:rgb(0, 0, 0);\n"
"color:rgb(0, 190, 0)"))
        self.qlw_history.setObjectName(_fromUtf8("qlw_history"))
        self.verticalLayout.addWidget(self.qlw_history)
        self.verticalLayout_3.addWidget(self.gbx_comandos)
        self.dck_lista_voos.setWidget(self.dwc_voos)
        wndMainPiloto.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dck_lista_voos)
        self.action_exit = QtGui.QAction(wndMainPiloto)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))

        self.retranslateUi(wndMainPiloto)
        QtCore.QMetaObject.connectSlotsByName(wndMainPiloto)

    def retranslateUi(self, wndMainPiloto):
        wndMainPiloto.setWindowTitle(_translate("wndMainPiloto", "Pilot 0.1 [Pilotagem]", None))
        self.lbl_title.setText(_translate("wndMainPiloto", "Lista de Vôos", None))
        self.gbx_comandos.setTitle(_translate("wndMainPiloto", "Comandos", None))
        self.btn_cmd_altitude.setText(_translate("wndMainPiloto", "altitude", None))
        self.btn_cancela.setText(_translate("wndMainPiloto", "cancela", None))
        self.btn_cod_spi.setText(_translate("wndMainPiloto", "SPI", None))
        self.btn_cmd_velocidade.setText(_translate("wndMainPiloto", "velocidade", None))
        self.btn_cod_ssr.setText(_translate("wndMainPiloto", "SSR", None))
        self.btn_cod_emg.setText(_translate("wndMainPiloto", "EMG", None))
        self.btn_cmd_direcao.setText(_translate("wndMainPiloto", "direção", None))
        self.btn_prc_esp.setText(_translate("wndMainPiloto", "espera", None))
        self.btn_prc_trj.setText(_translate("wndMainPiloto", "trajetória", None))
        self.btn_prc_dir_fixo.setText(_translate("wndMainPiloto", "dir.fixo", None))
        self.btn_prc_arr.setText(_translate("wndMainPiloto", "pouso", None))
        self.btn_prc_dep.setText(_translate("wndMainPiloto", "decolagem", None))
        self.btn_prc_apx.setText(_translate("wndMainPiloto", "aproximação", None))
        self.btn_prc_ape.setText(_translate("wndMainPiloto", "apx.perdida", None))
        self.btn_prc_ils.setText(_translate("wndMainPiloto", "ils", None))
        self.lbl_comando.setText(_translate("wndMainPiloto", "SIL1970: CURVA DIR 212 GRAUS", None))
        self.action_exit.setText(_translate("wndMainPiloto", "Sair", None))
        self.action_exit.setShortcut(_translate("wndMainPiloto", "Ctrl+X", None))

import resources_rc
