# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './strip_visil.ui'
#
# Created: Tue Oct 11 11:25:34 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_widStrip(object):
    def setupUi(self, widStrip):
        widStrip.setObjectName(_fromUtf8("widStrip"))
        widStrip.resize(335, 63)
        self.horizontalLayout = QtGui.QHBoxLayout(widStrip)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setMargin(1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.widget_5 = QtGui.QWidget(widStrip)
        self.widget_5.setStyleSheet(_fromUtf8("background-color: rgb(255, 170, 0);"))
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_5)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.lblCallsign = QtGui.QLabel(self.widget_5)
        self.lblCallsign.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 14pt \"Ubuntu Condensed\";\n"
""))
        self.lblCallsign.setObjectName(_fromUtf8("lblCallsign"))
        self.horizontalLayout_5.addWidget(self.lblCallsign)
        self.line = QtGui.QFrame(self.widget_5)
        self.line.setFrameShadow(QtGui.QFrame.Plain)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_5.addWidget(self.line)
        self.widget = QtGui.QWidget(self.widget_5)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setMargin(1)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.widget_2 = QtGui.QWidget(self.widget)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setMargin(1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.lblOrig = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblOrig.setFont(font)
        self.lblOrig.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblOrig.setObjectName(_fromUtf8("lblOrig"))
        self.horizontalLayout_2.addWidget(self.lblOrig)
        self.label = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.lblDest = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblDest.setFont(font)
        self.lblDest.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblDest.setObjectName(_fromUtf8("lblDest"))
        self.horizontalLayout_2.addWidget(self.lblDest)
        self.line_3 = QtGui.QFrame(self.widget_2)
        self.line_3.setFrameShadow(QtGui.QFrame.Plain)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_2.addWidget(self.line_3)
        self.lblRwy = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblRwy.setFont(font)
        self.lblRwy.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblRwy.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRwy.setObjectName(_fromUtf8("lblRwy"))
        self.horizontalLayout_2.addWidget(self.lblRwy)
        self.line_4 = QtGui.QFrame(self.widget_2)
        self.line_4.setFrameShadow(QtGui.QFrame.Plain)
        self.line_4.setLineWidth(1)
        self.line_4.setFrameShape(QtGui.QFrame.VLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_2.addWidget(self.line_4)
        self.lblAlt = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblAlt.setFont(font)
        self.lblAlt.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblAlt.setObjectName(_fromUtf8("lblAlt"))
        self.horizontalLayout_2.addWidget(self.lblAlt)
        self.line_5 = QtGui.QFrame(self.widget_2)
        self.line_5.setFrameShadow(QtGui.QFrame.Plain)
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtGui.QFrame.VLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.horizontalLayout_2.addWidget(self.line_5)
        self.lblProa = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblProa.setFont(font)
        self.lblProa.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblProa.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProa.setObjectName(_fromUtf8("lblProa"))
        self.horizontalLayout_2.addWidget(self.lblProa)
        self.line_6 = QtGui.QFrame(self.widget_2)
        self.line_6.setFrameShadow(QtGui.QFrame.Plain)
        self.line_6.setLineWidth(1)
        self.line_6.setFrameShape(QtGui.QFrame.VLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.horizontalLayout_2.addWidget(self.line_6)
        self.lblVel = QtGui.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblVel.setFont(font)
        self.lblVel.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblVel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblVel.setObjectName(_fromUtf8("lblVel"))
        self.horizontalLayout_2.addWidget(self.lblVel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        self.line_2 = QtGui.QFrame(self.widget)
        self.line_2.setFrameShadow(QtGui.QFrame.Plain)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout.addWidget(self.line_2)
        self.widget_3 = QtGui.QWidget(self.widget)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setMargin(1)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lblDsgn = QtGui.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu Condensed"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblDsgn.setFont(font)
        self.lblDsgn.setStyleSheet(_fromUtf8("color: rgb(0, 0, 0);\n"
"font: 10pt \"Ubuntu Condensed\";"))
        self.lblDsgn.setObjectName(_fromUtf8("lblDsgn"))
        self.horizontalLayout_3.addWidget(self.lblDsgn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout_5.addWidget(self.widget)
        self.horizontalLayout.addWidget(self.widget_5)

        self.retranslateUi(widStrip)
        QtCore.QMetaObject.connectSlotsByName(widStrip)

    def retranslateUi(self, widStrip):
        self.lblCallsign.setText(_translate("widStrip", "VRG1234", None))
        self.lblOrig.setText(_translate("widStrip", "BR01", None))
        self.label.setText(_translate("widStrip", " /", None))
        self.lblDest.setText(_translate("widStrip", "JFK", None))
        self.lblRwy.setText(_translate("widStrip", "W18", None))
        self.lblAlt.setText(_translate("widStrip", "100", None))
        self.lblProa.setText(_translate("widStrip", "254", None))
        self.lblVel.setText(_translate("widStrip", "350", None))
        self.lblDsgn.setText(_translate("widStrip", "B747-700", None))

