# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './wnd_main_visil.ui'
#
# Created: Tue Oct 11 11:25:34 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_wndMainVisil(object):
    def setupUi(self, wndMainVisil):
        wndMainVisil.setObjectName(_fromUtf8("wndMainVisil"))
        wndMainVisil.resize(1160, 889)
        wndMainVisil.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        self.centralwidget = QtGui.QWidget(wndMainVisil)
        self.centralwidget.setMouseTracking(True)
        self.centralwidget.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        wndMainVisil.setCentralWidget(self.centralwidget)
        self.status_bar = QtGui.QStatusBar(wndMainVisil)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        wndMainVisil.setStatusBar(self.status_bar)
        self.dock_lista_voos = QtGui.QDockWidget(wndMainVisil)
        self.dock_lista_voos.setStyleSheet(_fromUtf8(""))
        self.dock_lista_voos.setFloating(False)
        self.dock_lista_voos.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_lista_voos.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dock_lista_voos.setObjectName(_fromUtf8("dock_lista_voos"))
        self.dwc_strips = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dwc_strips.sizePolicy().hasHeightForWidth())
        self.dwc_strips.setSizePolicy(sizePolicy)
        self.dwc_strips.setObjectName(_fromUtf8("dwc_strips"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dwc_strips)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl_hora = QtGui.QLabel(self.dwc_strips)
        self.lbl_hora.setStyleSheet(_fromUtf8("font: 65 italic 26pt \"Courier New\";\n"
"color:rgb(0, 170, 0);"))
        self.lbl_hora.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_hora.setObjectName(_fromUtf8("lbl_hora"))
        self.verticalLayout_2.addWidget(self.lbl_hora)
        self.wid_lv = QtGui.QWidget(self.dwc_strips)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_lv.sizePolicy().hasHeightForWidth())
        self.wid_lv.setSizePolicy(sizePolicy)
        self.wid_lv.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: #729fcf;"))
        self.wid_lv.setObjectName(_fromUtf8("wid_lv"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.wid_lv)
        self.horizontalLayout_3.setSpacing(3)
        self.horizontalLayout_3.setMargin(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.lbl_icon = QtGui.QLabel(self.wid_lv)
        self.lbl_icon.setText(_fromUtf8(""))
        self.lbl_icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/tracks/compile16.png")))
        self.lbl_icon.setObjectName(_fromUtf8("lbl_icon"))
        self.horizontalLayout_3.addWidget(self.lbl_icon)
        self.lbl_title = QtGui.QLabel(self.wid_lv)
        self.lbl_title.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";"))
        self.lbl_title.setObjectName(_fromUtf8("lbl_title"))
        self.horizontalLayout_3.addWidget(self.lbl_title)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.wid_lv)
        self.qtv_stp = QtGui.QTableView(self.dwc_strips)
        self.qtv_stp.setObjectName(_fromUtf8("qtv_stp"))
        self.verticalLayout_2.addWidget(self.qtv_stp)
        self.qlw_strips = QtGui.QListWidget(self.dwc_strips)
        self.qlw_strips.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);"))
        self.qlw_strips.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.qlw_strips.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.qlw_strips.setResizeMode(QtGui.QListView.Adjust)
        self.qlw_strips.setObjectName(_fromUtf8("qlw_strips"))
        self.verticalLayout_2.addWidget(self.qlw_strips)
        self.dock_lista_voos.setWidget(self.dwc_strips)
        wndMainVisil.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_lista_voos)
        self.dock_toolbox = QtGui.QDockWidget(wndMainVisil)
        self.dock_toolbox.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dock_toolbox.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dock_toolbox.setObjectName(_fromUtf8("dock_toolbox"))
        self.widget = QtGui.QWidget()
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.wid_lv_2 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wid_lv_2.sizePolicy().hasHeightForWidth())
        self.wid_lv_2.setSizePolicy(sizePolicy)
        self.wid_lv_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"background-color: #729fcf;"))
        self.wid_lv_2.setObjectName(_fromUtf8("wid_lv_2"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.wid_lv_2)
        self.horizontalLayout_4.setSpacing(3)
        self.horizontalLayout_4.setMargin(3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lbl_icon_2 = QtGui.QLabel(self.wid_lv_2)
        self.lbl_icon_2.setText(_fromUtf8(""))
        self.lbl_icon_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/tracks/compile16.png")))
        self.lbl_icon_2.setObjectName(_fromUtf8("lbl_icon_2"))
        self.horizontalLayout_4.addWidget(self.lbl_icon_2)
        self.lbl_title_2 = QtGui.QLabel(self.wid_lv_2)
        self.lbl_title_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
"font: 14pt \"Arial\";"))
        self.lbl_title_2.setObjectName(_fromUtf8("lbl_title_2"))
        self.horizontalLayout_4.addWidget(self.lbl_title_2)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.wid_lv_2)
        self.tool_box = QtGui.QToolBox(self.widget)
        self.tool_box.setEnabled(True)
        self.tool_box.setObjectName(_fromUtf8("tool_box"))
        self.page_procs = QtGui.QWidget()
        self.page_procs.setGeometry(QtCore.QRect(0, 0, 274, 98))
        self.page_procs.setObjectName(_fromUtf8("page_procs"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.page_procs)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.tree_procs = QtGui.QTreeWidget(self.page_procs)
        self.tree_procs.setObjectName(_fromUtf8("tree_procs"))
        self.tree_procs.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_7.addWidget(self.tree_procs)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/tracks/execute.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_box.addItem(self.page_procs, icon, _fromUtf8(""))
        self.page_navaids = QtGui.QWidget()
        self.page_navaids.setGeometry(QtCore.QRect(0, 0, 274, 98))
        self.page_navaids.setObjectName(_fromUtf8("page_navaids"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.page_navaids)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.tree_navaids = QtGui.QTreeWidget(self.page_navaids)
        self.tree_navaids.setObjectName(_fromUtf8("tree_navaids"))
        self.tree_navaids.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_8.addWidget(self.tree_navaids)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/tracks/run16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_box.addItem(self.page_navaids, icon1, _fromUtf8(""))
        self.page_runways = QtGui.QWidget()
        self.page_runways.setGeometry(QtCore.QRect(0, 0, 274, 98))
        self.page_runways.setObjectName(_fromUtf8("page_runways"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.page_runways)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.tree_runways = QtGui.QTreeWidget(self.page_runways)
        self.tree_runways.setObjectName(_fromUtf8("tree_runways"))
        self.tree_runways.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_6.addWidget(self.tree_runways)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/linepointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_box.addItem(self.page_runways, icon2, _fromUtf8(""))
        self.page_landsacpe = QtGui.QWidget()
        self.page_landsacpe.setGeometry(QtCore.QRect(0, 0, 274, 73))
        self.page_landsacpe.setObjectName(_fromUtf8("page_landsacpe"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.page_landsacpe)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/pointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_box.addItem(self.page_landsacpe, icon3, _fromUtf8(""))
        self.page_maps = QtGui.QWidget()
        self.page_maps.setGeometry(QtCore.QRect(0, 0, 278, 94))
        self.page_maps.setObjectName(_fromUtf8("page_maps"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.page_maps)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.map_widget = QtGui.QWidget(self.page_maps)
        self.map_widget.setObjectName(_fromUtf8("map_widget"))
        self.layout = QtGui.QGridLayout(self.map_widget)
        self.layout.setMargin(0)
        self.layout.setObjectName(_fromUtf8("layout"))
        self.btn_trj = QtGui.QToolButton(self.map_widget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/linecolor.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_trj.setIcon(icon4)
        self.btn_trj.setIconSize(QtCore.QSize(50, 50))
        self.btn_trj.setCheckable(True)
        self.btn_trj.setObjectName(_fromUtf8("btn_trj"))
        self.layout.addWidget(self.btn_trj, 0, 0, 1, 1)
        self.btn_sub = QtGui.QToolButton(self.map_widget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/textpointer.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sub.setIcon(icon5)
        self.btn_sub.setIconSize(QtCore.QSize(50, 50))
        self.btn_sub.setCheckable(True)
        self.btn_sub.setObjectName(_fromUtf8("btn_sub"))
        self.layout.addWidget(self.btn_sub, 0, 1, 1, 1)
        self.btn_esp = QtGui.QToolButton(self.map_widget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_esp.setIcon(icon6)
        self.btn_esp.setIconSize(QtCore.QSize(50, 50))
        self.btn_esp.setCheckable(True)
        self.btn_esp.setObjectName(_fromUtf8("btn_esp"))
        self.layout.addWidget(self.btn_esp, 0, 3, 1, 1)
        self.btn_desc = QtGui.QToolButton(self.map_widget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/underline.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_desc.setIcon(icon7)
        self.btn_desc.setIconSize(QtCore.QSize(50, 50))
        self.btn_desc.setCheckable(True)
        self.btn_desc.setObjectName(_fromUtf8("btn_desc"))
        self.layout.addWidget(self.btn_desc, 0, 2, 1, 1)
        self.verticalLayout_3.addWidget(self.map_widget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/sendtoback.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tool_box.addItem(self.page_maps, icon8, _fromUtf8(""))
        self.page_backgrounds = QtGui.QWidget()
        self.page_backgrounds.setGeometry(QtCore.QRect(0, 0, 278, 94))
        self.page_backgrounds.setObjectName(_fromUtf8("page_backgrounds"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.page_backgrounds)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.background_widget = QtGui.QWidget(self.page_backgrounds)
        self.background_widget.setObjectName(_fromUtf8("background_widget"))
        self.backgroundLayout = QtGui.QGridLayout(self.background_widget)
        self.backgroundLayout.setMargin(0)
        self.backgroundLayout.setObjectName(_fromUtf8("backgroundLayout"))
        self.btn_gray = QtGui.QToolButton(self.background_widget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/background3.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_gray.setIcon(icon9)
        self.btn_gray.setIconSize(QtCore.QSize(50, 50))
        self.btn_gray.setCheckable(True)
        self.btn_gray.setObjectName(_fromUtf8("btn_gray"))
        self.backgroundLayout.addWidget(self.btn_gray, 0, 1, 1, 1)
        self.btn_blue = QtGui.QToolButton(self.background_widget)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/background1.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_blue.setIcon(icon10)
        self.btn_blue.setIconSize(QtCore.QSize(50, 50))
        self.btn_blue.setCheckable(True)
        self.btn_blue.setObjectName(_fromUtf8("btn_blue"))
        self.backgroundLayout.addWidget(self.btn_blue, 0, 0, 1, 1)
        self.btn_white = QtGui.QToolButton(self.background_widget)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/background2.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_white.setIcon(icon11)
        self.btn_white.setIconSize(QtCore.QSize(50, 50))
        self.btn_white.setCheckable(True)
        self.btn_white.setObjectName(_fromUtf8("btn_white"))
        self.backgroundLayout.addWidget(self.btn_white, 0, 3, 1, 1)
        self.btn_no_bckg = QtGui.QToolButton(self.background_widget)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/visir/background4.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_no_bckg.setIcon(icon12)
        self.btn_no_bckg.setIconSize(QtCore.QSize(50, 50))
        self.btn_no_bckg.setCheckable(True)
        self.btn_no_bckg.setObjectName(_fromUtf8("btn_no_bckg"))
        self.backgroundLayout.addWidget(self.btn_no_bckg, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.background_widget)
        self.tool_box.addItem(self.page_backgrounds, icon11, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tool_box)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.wid_cmd = QtGui.QWidget(self.widget)
        self.wid_cmd.setObjectName(_fromUtf8("wid_cmd"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.wid_cmd)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btn_zoom_in = QtGui.QToolButton(self.wid_cmd)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/tracks/fullscreen_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_in.setIcon(icon13)
        self.btn_zoom_in.setIconSize(QtCore.QSize(48, 48))
        self.btn_zoom_in.setObjectName(_fromUtf8("btn_zoom_in"))
        self.horizontalLayout_2.addWidget(self.btn_zoom_in)
        self.btn_zoom_out = QtGui.QToolButton(self.wid_cmd)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/tracks/view-restore_48.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_zoom_out.setIcon(icon14)
        self.btn_zoom_out.setIconSize(QtCore.QSize(48, 48))
        self.btn_zoom_out.setObjectName(_fromUtf8("btn_zoom_out"))
        self.horizontalLayout_2.addWidget(self.btn_zoom_out)
        self.verticalLayout.addWidget(self.wid_cmd)
        self.dock_toolbox.setWidget(self.widget)
        wndMainVisil.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.dock_toolbox)
        self.action_exit = QtGui.QAction(wndMainVisil)
        self.action_exit.setObjectName(_fromUtf8("action_exit"))

        self.retranslateUi(wndMainVisil)
        self.tool_box.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(wndMainVisil)

    def retranslateUi(self, wndMainVisil):
        wndMainVisil.setWindowTitle(_translate("wndMainVisil", "ViSIL 0.1 [Visualização]", None))
        self.lbl_hora.setText(_translate("wndMainVisil", "12:00:00", None))
        self.lbl_title.setText(_translate("wndMainVisil", "Lista de Vôos", None))
        self.lbl_title_2.setText(_translate("wndMainVisil", "Toolboxes", None))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_procs), _translate("wndMainVisil", "Procedures", None))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_navaids), _translate("wndMainVisil", "Navaids", None))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_runways), _translate("wndMainVisil", "Runways", None))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_landsacpe), _translate("wndMainVisil", "Landscape", None))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_maps), _translate("wndMainVisil", "Map Items", None))
        self.tool_box.setItemText(self.tool_box.indexOf(self.page_backgrounds), _translate("wndMainVisil", "Backgrounds", None))
        self.btn_zoom_out.setText(_translate("wndMainVisil", "...", None))
        self.action_exit.setText(_translate("wndMainVisil", "Sair", None))
        self.action_exit.setShortcut(_translate("wndMainVisil", "Ctrl+X", None))

import resources_visil_rc
