# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_prf_data_new.ui'
#
# Created: Tue Jan 26 11:33:06 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgPrfDataNEW(object):
    def setupUi(self, CDlgPrfDataNEW):
        CDlgPrfDataNEW.setObjectName(_fromUtf8("CDlgPrfDataNEW"))
        CDlgPrfDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        CDlgPrfDataNEW.resize(927, 766)
        CDlgPrfDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgPrfDataNEW.setSizeGripEnabled(True)
        CDlgPrfDataNEW.setModal(True)
        self.horizontalLayout_6 = QtGui.QHBoxLayout(CDlgPrfDataNEW)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.splitter = QtGui.QSplitter(CDlgPrfDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widPrfTab = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widPrfTab.sizePolicy().hasHeightForWidth())
        self.widPrfTab.setSizePolicy(sizePolicy)
        self.widPrfTab.setObjectName(_fromUtf8("widPrfTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widPrfTab)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qtwPrfTab = QtGui.QTableWidget(self.widPrfTab)
        self.qtwPrfTab.setObjectName(_fromUtf8("qtwPrfTab"))
        self.qtwPrfTab.setColumnCount(0)
        self.qtwPrfTab.setRowCount(0)
        self.verticalLayout.addWidget(self.qtwPrfTab)
        self.widPrfDat = QtGui.QWidget(self.splitter)
        self.widPrfDat.setObjectName(_fromUtf8("widPrfDat"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widPrfDat)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frmGrpID = QtGui.QFrame(self.widPrfDat)
        self.frmGrpID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGrpID.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGrpID.setObjectName(_fromUtf8("frmGrpID"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frmGrpID)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lblPrfID = QtGui.QLabel(self.frmGrpID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblPrfID.sizePolicy().hasHeightForWidth())
        self.lblPrfID.setSizePolicy(sizePolicy)
        self.lblPrfID.setObjectName(_fromUtf8("lblPrfID"))
        self.gridLayout_9.addWidget(self.lblPrfID, 0, 0, 1, 1)
        self.txtPrfID = QtGui.QLabel(self.frmGrpID)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 217, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 90, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 217, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 217, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 90, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 217, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 90, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(15, 255, 15))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(7, 217, 7))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 90, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 90, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 90, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 180, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.txtPrfID.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.txtPrfID.setFont(font)
        self.txtPrfID.setObjectName(_fromUtf8("txtPrfID"))
        self.gridLayout_9.addWidget(self.txtPrfID, 0, 1, 1, 1)
        self.lblPrfDesc = QtGui.QLabel(self.frmGrpID)
        self.lblPrfDesc.setObjectName(_fromUtf8("lblPrfDesc"))
        self.gridLayout_9.addWidget(self.lblPrfDesc, 1, 0, 1, 1)
        self.qlePrfDesc = QtGui.QLineEdit(self.frmGrpID)
        self.qlePrfDesc.setObjectName(_fromUtf8("qlePrfDesc"))
        self.gridLayout_9.addWidget(self.qlePrfDesc, 1, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frmGrpID)
        self.widget = QtGui.QWidget(self.widPrfDat)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.widget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gbxMax = QtGui.QGroupBox(self.widget)
        self.gbxMax.setObjectName(_fromUtf8("gbxMax"))
        self.gridLayout = QtGui.QGridLayout(self.gbxMax)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblMaxAlt = QtGui.QLabel(self.gbxMax)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxAlt.sizePolicy().hasHeightForWidth())
        self.lblMaxAlt.setSizePolicy(sizePolicy)
        self.lblMaxAlt.setObjectName(_fromUtf8("lblMaxAlt"))
        self.gridLayout.addWidget(self.lblMaxAlt, 1, 0, 1, 1)
        self.spinBox_3 = QtGui.QSpinBox(self.gbxMax)
        self.spinBox_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_3.setObjectName(_fromUtf8("spinBox_3"))
        self.gridLayout.addWidget(self.spinBox_3, 5, 1, 1, 1)
        self.lblMaxVelTax = QtGui.QLabel(self.gbxMax)
        self.lblMaxVelTax.setObjectName(_fromUtf8("lblMaxVelTax"))
        self.gridLayout.addWidget(self.lblMaxVelTax, 5, 0, 1, 1)
        self.spinBox = QtGui.QSpinBox(self.gbxMax)
        self.spinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.gridLayout.addWidget(self.spinBox, 1, 1, 1, 1)
        self.lblMaxVel = QtGui.QLabel(self.gbxMax)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMaxVel.sizePolicy().hasHeightForWidth())
        self.lblMaxVel.setSizePolicy(sizePolicy)
        self.lblMaxVel.setObjectName(_fromUtf8("lblMaxVel"))
        self.gridLayout.addWidget(self.lblMaxVel, 2, 0, 1, 1)
        self.spinBox_2 = QtGui.QSpinBox(self.gbxMax)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_2.setObjectName(_fromUtf8("spinBox_2"))
        self.gridLayout.addWidget(self.spinBox_2, 2, 1, 1, 1)
        self.horizontalLayout.addWidget(self.gbxMax)
        self.gbxVoo = QtGui.QGroupBox(self.widget)
        self.gbxVoo.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.gbxVoo.setObjectName(_fromUtf8("gbxVoo"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbxVoo)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblVooDac = QtGui.QLabel(self.gbxVoo)
        self.lblVooDac.setObjectName(_fromUtf8("lblVooDac"))
        self.gridLayout_2.addWidget(self.lblVooDac, 1, 0, 1, 1)
        self.lblVooAcc = QtGui.QLabel(self.gbxVoo)
        self.lblVooAcc.setObjectName(_fromUtf8("lblVooAcc"))
        self.gridLayout_2.addWidget(self.lblVooAcc, 0, 0, 1, 1)
        self.spinBox_4 = QtGui.QSpinBox(self.gbxVoo)
        self.spinBox_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_4.setObjectName(_fromUtf8("spinBox_4"))
        self.gridLayout_2.addWidget(self.spinBox_4, 0, 1, 1, 1)
        self.lblVooDummy_1 = QtGui.QLabel(self.gbxVoo)
        self.lblVooDummy_1.setText(_fromUtf8(""))
        self.lblVooDummy_1.setObjectName(_fromUtf8("lblVooDummy_1"))
        self.gridLayout_2.addWidget(self.lblVooDummy_1, 3, 0, 1, 1)
        self.spinBox_5 = QtGui.QSpinBox(self.gbxVoo)
        self.spinBox_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.gridLayout_2.addWidget(self.spinBox_5, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.gbxVoo)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_2 = QtGui.QWidget(self.widPrfDat)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gbxDep = QtGui.QGroupBox(self.widget_2)
        self.gbxDep.setObjectName(_fromUtf8("gbxDep"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbxDep)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.spinBox_6 = QtGui.QSpinBox(self.gbxDep)
        self.spinBox_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.gridLayout_7.addWidget(self.spinBox_6, 1, 1, 1, 1)
        self.lblDepVelMin = QtGui.QLabel(self.gbxDep)
        self.lblDepVelMin.setObjectName(_fromUtf8("lblDepVelMin"))
        self.gridLayout_7.addWidget(self.lblDepVelMin, 1, 0, 1, 1)
        self.spinBox_7 = QtGui.QSpinBox(self.gbxDep)
        self.spinBox_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.gridLayout_7.addWidget(self.spinBox_7, 0, 1, 1, 1)
        self.lblDepAccMin = QtGui.QLabel(self.gbxDep)
        self.lblDepAccMin.setObjectName(_fromUtf8("lblDepAccMin"))
        self.gridLayout_7.addWidget(self.lblDepAccMin, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbxDep)
        self.gbxArr = QtGui.QGroupBox(self.widget_2)
        self.gbxArr.setObjectName(_fromUtf8("gbxArr"))
        self.gridLayout_8 = QtGui.QGridLayout(self.gbxArr)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblArrDacMax = QtGui.QLabel(self.gbxArr)
        self.lblArrDacMax.setObjectName(_fromUtf8("lblArrDacMax"))
        self.gridLayout_8.addWidget(self.lblArrDacMax, 0, 0, 1, 1)
        self.spinBox_8 = QtGui.QSpinBox(self.gbxArr)
        self.spinBox_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_8.setObjectName(_fromUtf8("spinBox_8"))
        self.gridLayout_8.addWidget(self.spinBox_8, 0, 1, 1, 1)
        self.lblArrVelMax = QtGui.QLabel(self.gbxArr)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblArrVelMax.sizePolicy().hasHeightForWidth())
        self.lblArrVelMax.setSizePolicy(sizePolicy)
        self.lblArrVelMax.setObjectName(_fromUtf8("lblArrVelMax"))
        self.gridLayout_8.addWidget(self.lblArrVelMax, 1, 0, 1, 1)
        self.spinBox_9 = QtGui.QSpinBox(self.gbxArr)
        self.spinBox_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_9.setObjectName(_fromUtf8("spinBox_9"))
        self.gridLayout_8.addWidget(self.spinBox_9, 1, 1, 1, 1)
        self.horizontalLayout_2.addWidget(self.gbxArr)
        self.verticalLayout_2.addWidget(self.widget_2)
        self.widget_3 = QtGui.QWidget(self.widPrfDat)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widget_3)
        self.horizontalLayout_5.setMargin(0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.gbxSub = QtGui.QGroupBox(self.widget_3)
        self.gbxSub.setObjectName(_fromUtf8("gbxSub"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gbxSub)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.lblSubRaz = QtGui.QLabel(self.gbxSub)
        self.lblSubRaz.setObjectName(_fromUtf8("lblSubRaz"))
        self.gridLayout_5.addWidget(self.lblSubRaz, 3, 0, 1, 1)
        self.spinBox_11 = QtGui.QSpinBox(self.gbxSub)
        self.spinBox_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_11.setObjectName(_fromUtf8("spinBox_11"))
        self.gridLayout_5.addWidget(self.spinBox_11, 3, 1, 1, 1)
        self.lblSubVel = QtGui.QLabel(self.gbxSub)
        self.lblSubVel.setObjectName(_fromUtf8("lblSubVel"))
        self.gridLayout_5.addWidget(self.lblSubVel, 2, 0, 1, 1)
        self.spinBox_10 = QtGui.QSpinBox(self.gbxSub)
        self.spinBox_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_10.setObjectName(_fromUtf8("spinBox_10"))
        self.gridLayout_5.addWidget(self.spinBox_10, 2, 1, 1, 1)
        self.horizontalLayout_5.addWidget(self.gbxSub)
        self.gbxDsc = QtGui.QGroupBox(self.widget_3)
        self.gbxDsc.setObjectName(_fromUtf8("gbxDsc"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gbxDsc)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lblDscRaz = QtGui.QLabel(self.gbxDsc)
        self.lblDscRaz.setObjectName(_fromUtf8("lblDscRaz"))
        self.gridLayout_6.addWidget(self.lblDscRaz, 4, 0, 1, 1)
        self.spinBox_13 = QtGui.QSpinBox(self.gbxDsc)
        self.spinBox_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_13.setObjectName(_fromUtf8("spinBox_13"))
        self.gridLayout_6.addWidget(self.spinBox_13, 4, 1, 1, 1)
        self.spinBox_12 = QtGui.QSpinBox(self.gbxDsc)
        self.spinBox_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_12.setObjectName(_fromUtf8("spinBox_12"))
        self.gridLayout_6.addWidget(self.spinBox_12, 3, 1, 1, 1)
        self.lblDscRazMax = QtGui.QLabel(self.gbxDsc)
        self.lblDscRazMax.setObjectName(_fromUtf8("lblDscRazMax"))
        self.gridLayout_6.addWidget(self.lblDscRazMax, 3, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.gbxDsc)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_4 = QtGui.QWidget(self.widPrfDat)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.widget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.gbxCrvRaz = QtGui.QGroupBox(self.widget_4)
        self.gbxCrvRaz.setObjectName(_fromUtf8("gbxCrvRaz"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gbxCrvRaz)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lblCrvRazRta = QtGui.QLabel(self.gbxCrvRaz)
        self.lblCrvRazRta.setObjectName(_fromUtf8("lblCrvRazRta"))
        self.gridLayout_4.addWidget(self.lblCrvRazRta, 0, 0, 1, 1)
        self.spinBox_14 = QtGui.QSpinBox(self.gbxCrvRaz)
        self.spinBox_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_14.setObjectName(_fromUtf8("spinBox_14"))
        self.gridLayout_4.addWidget(self.spinBox_14, 0, 1, 1, 1)
        self.lblCrvRazTrf = QtGui.QLabel(self.gbxCrvRaz)
        self.lblCrvRazTrf.setObjectName(_fromUtf8("lblCrvRazTrf"))
        self.gridLayout_4.addWidget(self.lblCrvRazTrf, 2, 0, 1, 1)
        self.spinBox_15 = QtGui.QSpinBox(self.gbxCrvRaz)
        self.spinBox_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_15.setObjectName(_fromUtf8("spinBox_15"))
        self.gridLayout_4.addWidget(self.spinBox_15, 1, 1, 1, 1)
        self.lblCrvRazSlo = QtGui.QLabel(self.gbxCrvRaz)
        self.lblCrvRazSlo.setObjectName(_fromUtf8("lblCrvRazSlo"))
        self.gridLayout_4.addWidget(self.lblCrvRazSlo, 1, 0, 1, 1)
        self.spinBox_16 = QtGui.QSpinBox(self.gbxCrvRaz)
        self.spinBox_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_16.setObjectName(_fromUtf8("spinBox_16"))
        self.gridLayout_4.addWidget(self.spinBox_16, 2, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.gbxCrvRaz)
        self.gbxCkt = QtGui.QGroupBox(self.widget_4)
        self.gbxCkt.setObjectName(_fromUtf8("gbxCkt"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gbxCkt)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.spinBox_18 = QtGui.QSpinBox(self.gbxCkt)
        self.spinBox_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_18.setObjectName(_fromUtf8("spinBox_18"))
        self.gridLayout_3.addWidget(self.spinBox_18, 2, 1, 1, 1)
        self.spinBox_17 = QtGui.QSpinBox(self.gbxCkt)
        self.spinBox_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_17.setObjectName(_fromUtf8("spinBox_17"))
        self.gridLayout_3.addWidget(self.spinBox_17, 0, 1, 1, 1)
        self.lblCkt = QtGui.QLabel(self.gbxCkt)
        self.lblCkt.setObjectName(_fromUtf8("lblCkt"))
        self.gridLayout_3.addWidget(self.lblCkt, 0, 0, 1, 1)
        self.lblCktAlt = QtGui.QLabel(self.gbxCkt)
        self.lblCktAlt.setObjectName(_fromUtf8("lblCktAlt"))
        self.gridLayout_3.addWidget(self.lblCktAlt, 2, 0, 1, 1)
        self.lblCktVel = QtGui.QLabel(self.gbxCkt)
        self.lblCktVel.setObjectName(_fromUtf8("lblCktVel"))
        self.gridLayout_3.addWidget(self.lblCktVel, 3, 0, 1, 1)
        self.spinBox_19 = QtGui.QSpinBox(self.gbxCkt)
        self.spinBox_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.spinBox_19.setObjectName(_fromUtf8("spinBox_19"))
        self.gridLayout_3.addWidget(self.spinBox_19, 3, 1, 1, 1)
        self.horizontalLayout_4.addWidget(self.gbxCkt)
        self.verticalLayout_2.addWidget(self.widget_4)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frmGrpBtn_1 = QtGui.QFrame(self.widPrfDat)
        self.frmGrpBtn_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGrpBtn_1.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGrpBtn_1.setObjectName(_fromUtf8("frmGrpBtn_1"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.frmGrpBtn_1)
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.btnNew = QtGui.QPushButton(self.frmGrpBtn_1)
        self.btnNew.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.horizontalLayout_8.addWidget(self.btnNew)
        self.btnDel = QtGui.QPushButton(self.frmGrpBtn_1)
        self.btnDel.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDel.setIcon(icon1)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.horizontalLayout_8.addWidget(self.btnDel)
        self.bbxPrfTab = QtGui.QDialogButtonBox(self.frmGrpBtn_1)
        self.bbxPrfTab.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbxPrfTab.setObjectName(_fromUtf8("bbxPrfTab"))
        self.horizontalLayout_8.addWidget(self.bbxPrfTab)
        self.verticalLayout_2.addWidget(self.frmGrpBtn_1)
        self.horizontalLayout_6.addWidget(self.splitter)

        self.retranslateUi(CDlgPrfDataNEW)
        QtCore.QMetaObject.connectSlotsByName(CDlgPrfDataNEW)

    def retranslateUi(self, CDlgPrfDataNEW):
        CDlgPrfDataNEW.setWindowTitle(_translate("CDlgPrfDataNEW", "TrackS [ Edição de Performances ]", None))
        self.lblPrfID.setText(_translate("CDlgPrfDataNEW", "Indicativo:", None))
        self.txtPrfID.setText(_translate("CDlgPrfDataNEW", "B707", None))
        self.lblPrfDesc.setText(_translate("CDlgPrfDataNEW", "Descrição:", None))
        self.gbxMax.setTitle(_translate("CDlgPrfDataNEW", "Performance", None))
        self.lblMaxAlt.setText(_translate("CDlgPrfDataNEW", "Altitude máxima:", None))
        self.spinBox_3.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblMaxVelTax.setText(_translate("CDlgPrfDataNEW", "Velocidade máxima de taxi:", None))
        self.spinBox.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblMaxVel.setText(_translate("CDlgPrfDataNEW", "Velocidade máxima:", None))
        self.spinBox_2.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.gbxVoo.setTitle(_translate("CDlgPrfDataNEW", "Vôo", None))
        self.lblVooDac.setText(_translate("CDlgPrfDataNEW", "Desaceleração de vôo:", None))
        self.lblVooAcc.setText(_translate("CDlgPrfDataNEW", "Aceleração de vôo:", None))
        self.spinBox_4.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.spinBox_5.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.gbxDep.setTitle(_translate("CDlgPrfDataNEW", "Decolagem", None))
        self.spinBox_6.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblDepVelMin.setText(_translate("CDlgPrfDataNEW", "Velocidade mín. de decolagem:", None))
        self.spinBox_7.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblDepAccMin.setText(_translate("CDlgPrfDataNEW", "Aceleração mín. de decolagem:", None))
        self.gbxArr.setTitle(_translate("CDlgPrfDataNEW", "Pouso", None))
        self.lblArrDacMax.setText(_translate("CDlgPrfDataNEW", "Desaceleração máx. de pouso:", None))
        self.spinBox_8.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblArrVelMax.setText(_translate("CDlgPrfDataNEW", "Velocidade máxima de pouso:", None))
        self.spinBox_9.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.gbxSub.setTitle(_translate("CDlgPrfDataNEW", "Subida", None))
        self.lblSubRaz.setText(_translate("CDlgPrfDataNEW", "Razão de subida:", None))
        self.spinBox_11.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblSubVel.setText(_translate("CDlgPrfDataNEW", "Velocidade de subida:", None))
        self.spinBox_10.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.gbxDsc.setTitle(_translate("CDlgPrfDataNEW", "Descida", None))
        self.lblDscRaz.setText(_translate("CDlgPrfDataNEW", "Razão de descida:", None))
        self.spinBox_13.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.spinBox_12.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblDscRazMax.setText(_translate("CDlgPrfDataNEW", "Razão máxima de descida:", None))
        self.gbxCrvRaz.setTitle(_translate("CDlgPrfDataNEW", "Razão de curva", None))
        self.lblCrvRazRta.setText(_translate("CDlgPrfDataNEW", "Razão de curva em rota:", None))
        self.spinBox_14.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblCrvRazTrf.setText(_translate("CDlgPrfDataNEW", "Razão de curva em tráfego:", None))
        self.spinBox_15.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblCrvRazSlo.setText(_translate("CDlgPrfDataNEW", "Razão de curva no solo:", None))
        self.spinBox_16.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.gbxCkt.setTitle(_translate("CDlgPrfDataNEW", "Circuito", None))
        self.spinBox_18.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.spinBox_17.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.lblCkt.setText(_translate("CDlgPrfDataNEW", "Circuito:", None))
        self.lblCktAlt.setText(_translate("CDlgPrfDataNEW", "Altitude de circuito:", None))
        self.lblCktVel.setText(_translate("CDlgPrfDataNEW", "Velocidade de circuito:", None))
        self.spinBox_19.setSuffix(_translate("CDlgPrfDataNEW", " kt", None))
        self.btnNew.setText(_translate("CDlgPrfDataNEW", "Nova", None))
        self.btnDel.setText(_translate("CDlgPrfDataNEW", "Remove", None))

import qrc_resources_rc
