# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_exe_edit_new.ui'
#
# Created: Wed Dec  7 12:55:06 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgExeEditNEW(object):
    def setupUi(self, CDlgExeEditNEW):
        CDlgExeEditNEW.setObjectName(_fromUtf8("CDlgExeEditNEW"))
        CDlgExeEditNEW.resize(554, 715)
        CDlgExeEditNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgExeEditNEW.setSizeGripEnabled(True)
        CDlgExeEditNEW.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(CDlgExeEditNEW)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.frmID = QtGui.QFrame(CDlgExeEditNEW)
        self.frmID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmID.setFrameShadow(QtGui.QFrame.Raised)
        self.frmID.setLineWidth(1)
        self.frmID.setObjectName(_fromUtf8("frmID"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.frmID)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblNome = QtGui.QLabel(self.frmID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblNome.sizePolicy().hasHeightForWidth())
        self.lblNome.setSizePolicy(sizePolicy)
        self.lblNome.setObjectName(_fromUtf8("lblNome"))
        self.horizontalLayout.addWidget(self.lblNome)
        self.qleNome = QtGui.QLineEdit(self.frmID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleNome.sizePolicy().hasHeightForWidth())
        self.qleNome.setSizePolicy(sizePolicy)
        self.qleNome.setObjectName(_fromUtf8("qleNome"))
        self.horizontalLayout.addWidget(self.qleNome)
        self.lblDesc = QtGui.QLabel(self.frmID)
        self.lblDesc.setObjectName(_fromUtf8("lblDesc"))
        self.horizontalLayout.addWidget(self.lblDesc)
        self.qleDesc = QtGui.QLineEdit(self.frmID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qleDesc.sizePolicy().hasHeightForWidth())
        self.qleDesc.setSizePolicy(sizePolicy)
        self.qleDesc.setObjectName(_fromUtf8("qleDesc"))
        self.horizontalLayout.addWidget(self.qleDesc)
        self.verticalLayout.addWidget(self.frmID)
        self.frmGrl = QtGui.QFrame(CDlgExeEditNEW)
        self.frmGrl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmGrl.setFrameShadow(QtGui.QFrame.Raised)
        self.frmGrl.setObjectName(_fromUtf8("frmGrl"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmGrl)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gbxGrl = QtGui.QGroupBox(self.frmGrl)
        self.gbxGrl.setObjectName(_fromUtf8("gbxGrl"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.gbxGrl)
        self.horizontalLayout_7.setContentsMargins(9, -1, -1, -1)
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.widGrl1 = QtGui.QWidget(self.gbxGrl)
        self.widGrl1.setObjectName(_fromUtf8("widGrl1"))
        self.gridLayout_8 = QtGui.QGridLayout(self.widGrl1)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblGrlCena = QtGui.QLabel(self.widGrl1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGrlCena.sizePolicy().hasHeightForWidth())
        self.lblGrlCena.setSizePolicy(sizePolicy)
        self.lblGrlCena.setObjectName(_fromUtf8("lblGrlCena"))
        self.gridLayout_8.addWidget(self.lblGrlCena, 0, 0, 1, 1)
        self.cbxGrlCena = QtGui.QComboBox(self.widGrl1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbxGrlCena.sizePolicy().hasHeightForWidth())
        self.cbxGrlCena.setSizePolicy(sizePolicy)
        self.cbxGrlCena.setMaxVisibleItems(5)
        self.cbxGrlCena.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cbxGrlCena.setObjectName(_fromUtf8("cbxGrlCena"))
        self.gridLayout_8.addWidget(self.cbxGrlCena, 0, 1, 1, 1)
        self.lblGrlIni = QtGui.QLabel(self.widGrl1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblGrlIni.sizePolicy().hasHeightForWidth())
        self.lblGrlIni.setSizePolicy(sizePolicy)
        self.lblGrlIni.setObjectName(_fromUtf8("lblGrlIni"))
        self.gridLayout_8.addWidget(self.lblGrlIni, 2, 0, 1, 1)
        self.widGrlIni = QtGui.QWidget(self.widGrl1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widGrlIni.sizePolicy().hasHeightForWidth())
        self.widGrlIni.setSizePolicy(sizePolicy)
        self.widGrlIni.setObjectName(_fromUtf8("widGrlIni"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.widGrlIni)
        self.horizontalLayout_5.setSpacing(1)
        self.horizontalLayout_5.setMargin(1)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.qsbGrlIniHor = QtGui.QSpinBox(self.widGrlIni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbGrlIniHor.sizePolicy().hasHeightForWidth())
        self.qsbGrlIniHor.setSizePolicy(sizePolicy)
        self.qsbGrlIniHor.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbGrlIniHor.setMaximum(23)
        self.qsbGrlIniHor.setObjectName(_fromUtf8("qsbGrlIniHor"))
        self.horizontalLayout_5.addWidget(self.qsbGrlIniHor)
        self.qsbGrlIniMin = QtGui.QSpinBox(self.widGrlIni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbGrlIniMin.sizePolicy().hasHeightForWidth())
        self.qsbGrlIniMin.setSizePolicy(sizePolicy)
        self.qsbGrlIniMin.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbGrlIniMin.setMaximum(59)
        self.qsbGrlIniMin.setSingleStep(5)
        self.qsbGrlIniMin.setObjectName(_fromUtf8("qsbGrlIniMin"))
        self.horizontalLayout_5.addWidget(self.qsbGrlIniMin)
        self.qsbGrlIniSeg = QtGui.QSpinBox(self.widGrlIni)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbGrlIniSeg.sizePolicy().hasHeightForWidth())
        self.qsbGrlIniSeg.setSizePolicy(sizePolicy)
        self.qsbGrlIniSeg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbGrlIniSeg.setMaximum(59)
        self.qsbGrlIniSeg.setSingleStep(5)
        self.qsbGrlIniSeg.setObjectName(_fromUtf8("qsbGrlIniSeg"))
        self.horizontalLayout_5.addWidget(self.qsbGrlIniSeg)
        self.gridLayout_8.addWidget(self.widGrlIni, 2, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.widGrl1)
        self.widGrl2 = QtGui.QWidget(self.gbxGrl)
        self.widGrl2.setObjectName(_fromUtf8("widGrl2"))
        self.gridLayout = QtGui.QGridLayout(self.widGrl2)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lblGrlRnd = QtGui.QLabel(self.widGrl2)
        self.lblGrlRnd.setObjectName(_fromUtf8("lblGrlRnd"))
        self.gridLayout.addWidget(self.lblGrlRnd, 2, 0, 1, 1)
        self.qsbGrlRnd = QtGui.QSpinBox(self.widGrl2)
        self.qsbGrlRnd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbGrlRnd.setMaximum(100)
        self.qsbGrlRnd.setSingleStep(10)
        self.qsbGrlRnd.setObjectName(_fromUtf8("qsbGrlRnd"))
        self.gridLayout.addWidget(self.qsbGrlRnd, 2, 1, 1, 1)
        self.lblGrlAnvQtd = QtGui.QLabel(self.widGrl2)
        self.lblGrlAnvQtd.setObjectName(_fromUtf8("lblGrlAnvQtd"))
        self.gridLayout.addWidget(self.lblGrlAnvQtd, 1, 0, 1, 1)
        self.txtGrlAnvQtd = QtGui.QLabel(self.widGrl2)
        self.txtGrlAnvQtd.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.txtGrlAnvQtd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtGrlAnvQtd.setObjectName(_fromUtf8("txtGrlAnvQtd"))
        self.gridLayout.addWidget(self.txtGrlAnvQtd, 1, 1, 1, 1)
        self.horizontalLayout_7.addWidget(self.widGrl2)
        self.verticalLayout_2.addWidget(self.gbxGrl)
        self.verticalLayout.addWidget(self.frmGrl)
        self.frmMet = QtGui.QFrame(CDlgExeEditNEW)
        self.frmMet.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmMet.setFrameShadow(QtGui.QFrame.Raised)
        self.frmMet.setObjectName(_fromUtf8("frmMet"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.frmMet)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gbxMet = QtGui.QGroupBox(self.frmMet)
        self.gbxMet.setObjectName(_fromUtf8("gbxMet"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.gbxMet)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.widMet1 = QtGui.QWidget(self.gbxMet)
        self.widMet1.setObjectName(_fromUtf8("widMet1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widMet1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lblMetVnt = QtGui.QLabel(self.widMet1)
        self.lblMetVnt.setObjectName(_fromUtf8("lblMetVnt"))
        self.gridLayout_2.addWidget(self.lblMetVnt, 0, 0, 1, 1)
        self.lblMetVntDir = QtGui.QLabel(self.widMet1)
        self.lblMetVntDir.setObjectName(_fromUtf8("lblMetVntDir"))
        self.gridLayout_2.addWidget(self.lblMetVntDir, 0, 2, 1, 1)
        self.qsbMetVntDir = QtGui.QSpinBox(self.widMet1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbMetVntDir.sizePolicy().hasHeightForWidth())
        self.qsbMetVntDir.setSizePolicy(sizePolicy)
        self.qsbMetVntDir.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbMetVntDir.setMaximum(360)
        self.qsbMetVntDir.setSingleStep(5)
        self.qsbMetVntDir.setProperty("value", 0)
        self.qsbMetVntDir.setObjectName(_fromUtf8("qsbMetVntDir"))
        self.gridLayout_2.addWidget(self.qsbMetVntDir, 0, 3, 1, 1)
        self.lblMetVntVel = QtGui.QLabel(self.widMet1)
        self.lblMetVntVel.setObjectName(_fromUtf8("lblMetVntVel"))
        self.gridLayout_2.addWidget(self.lblMetVntVel, 0, 4, 1, 1)
        self.qsbMetVntVel = QtGui.QSpinBox(self.widMet1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbMetVntVel.sizePolicy().hasHeightForWidth())
        self.qsbMetVntVel.setSizePolicy(sizePolicy)
        self.qsbMetVntVel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbMetVntVel.setMaximum(500)
        self.qsbMetVntVel.setSingleStep(10)
        self.qsbMetVntVel.setObjectName(_fromUtf8("qsbMetVntVel"))
        self.gridLayout_2.addWidget(self.qsbMetVntVel, 0, 5, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        self.verticalLayout_6.addWidget(self.widMet1)
        self.widMet2 = QtGui.QWidget(self.gbxMet)
        self.widMet2.setObjectName(_fromUtf8("widMet2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.widMet2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(20)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lblMetTto = QtGui.QLabel(self.widMet2)
        self.lblMetTto.setObjectName(_fromUtf8("lblMetTto"))
        self.gridLayout_3.addWidget(self.lblMetTto, 0, 0, 1, 1)
        self.qsbMetTeto = QtGui.QSpinBox(self.widMet2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbMetTeto.sizePolicy().hasHeightForWidth())
        self.qsbMetTeto.setSizePolicy(sizePolicy)
        self.qsbMetTeto.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbMetTeto.setMaximum(80000)
        self.qsbMetTeto.setSingleStep(1000)
        self.qsbMetTeto.setObjectName(_fromUtf8("qsbMetTeto"))
        self.gridLayout_3.addWidget(self.qsbMetTeto, 0, 1, 1, 1)
        self.lblMetVis = QtGui.QLabel(self.widMet2)
        self.lblMetVis.setObjectName(_fromUtf8("lblMetVis"))
        self.gridLayout_3.addWidget(self.lblMetVis, 2, 0, 1, 1)
        self.qsbMetVisi = QtGui.QSpinBox(self.widMet2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbMetVisi.sizePolicy().hasHeightForWidth())
        self.qsbMetVisi.setSizePolicy(sizePolicy)
        self.qsbMetVisi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbMetVisi.setMaximum(20000)
        self.qsbMetVisi.setSingleStep(1000)
        self.qsbMetVisi.setProperty("value", 0)
        self.qsbMetVisi.setObjectName(_fromUtf8("qsbMetVisi"))
        self.gridLayout_3.addWidget(self.qsbMetVisi, 2, 1, 1, 1)
        self.lblMetTmp = QtGui.QLabel(self.widMet2)
        self.lblMetTmp.setObjectName(_fromUtf8("lblMetTmp"))
        self.gridLayout_3.addWidget(self.lblMetTmp, 0, 2, 1, 1)
        self.qsbMetTemp = QtGui.QSpinBox(self.widMet2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbMetTemp.sizePolicy().hasHeightForWidth())
        self.qsbMetTemp.setSizePolicy(sizePolicy)
        self.qsbMetTemp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbMetTemp.setMinimum(-50)
        self.qsbMetTemp.setMaximum(80)
        self.qsbMetTemp.setSingleStep(2)
        self.qsbMetTemp.setObjectName(_fromUtf8("qsbMetTemp"))
        self.gridLayout_3.addWidget(self.qsbMetTemp, 0, 3, 1, 1)
        self.lblMetPrs = QtGui.QLabel(self.widMet2)
        self.lblMetPrs.setObjectName(_fromUtf8("lblMetPrs"))
        self.gridLayout_3.addWidget(self.lblMetPrs, 2, 2, 1, 1)
        self.qsbMetPres = QtGui.QSpinBox(self.widMet2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.qsbMetPres.sizePolicy().hasHeightForWidth())
        self.qsbMetPres.setSizePolicy(sizePolicy)
        self.qsbMetPres.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qsbMetPres.setMaximum(2000)
        self.qsbMetPres.setSingleStep(100)
        self.qsbMetPres.setObjectName(_fromUtf8("qsbMetPres"))
        self.gridLayout_3.addWidget(self.qsbMetPres, 2, 3, 1, 1)
        self.verticalLayout_6.addWidget(self.widMet2)
        self.verticalLayout_4.addWidget(self.gbxMet)
        self.verticalLayout.addWidget(self.frmMet)
        self.frmAnv = QtGui.QFrame(CDlgExeEditNEW)
        self.frmAnv.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmAnv.setFrameShadow(QtGui.QFrame.Raised)
        self.frmAnv.setObjectName(_fromUtf8("frmAnv"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.frmAnv)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gbxAnv = QtGui.QGroupBox(self.frmAnv)
        self.gbxAnv.setObjectName(_fromUtf8("gbxAnv"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbxAnv)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.qtwTabAnv = QtGui.QTableWidget(self.gbxAnv)
        self.qtwTabAnv.setObjectName(_fromUtf8("qtwTabAnv"))
        self.qtwTabAnv.setColumnCount(0)
        self.qtwTabAnv.setRowCount(0)
        self.verticalLayout_3.addWidget(self.qtwTabAnv)
        self.verticalLayout_5.addWidget(self.gbxAnv)
        self.widBtn = QtGui.QWidget(self.frmAnv)
        self.widBtn.setObjectName(_fromUtf8("widBtn"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.widBtn)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnNew = QtGui.QPushButton(self.widBtn)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.horizontalLayout_2.addWidget(self.btnNew)
        self.btnEdit = QtGui.QPushButton(self.widBtn)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEdit.setIcon(icon1)
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.horizontalLayout_2.addWidget(self.btnEdit)
        self.btnRem = QtGui.QPushButton(self.widBtn)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRem.setIcon(icon2)
        self.btnRem.setObjectName(_fromUtf8("btnRem"))
        self.horizontalLayout_2.addWidget(self.btnRem)
        self.verticalLayout_5.addWidget(self.widBtn)
        self.verticalLayout.addWidget(self.frmAnv)
        self.bbxExeEdit = QtGui.QWidget(CDlgExeEditNEW)
        self.bbxExeEdit.setObjectName(_fromUtf8("bbxExeEdit"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.bbxExeEdit)
        self.horizontalLayout_6.setMargin(0)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.btnFirst = QtGui.QPushButton(self.bbxExeEdit)
        self.btnFirst.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnFirst.setIcon(icon3)
        self.btnFirst.setObjectName(_fromUtf8("btnFirst"))
        self.horizontalLayout_6.addWidget(self.btnFirst)
        self.btnPrev = QtGui.QPushButton(self.bbxExeEdit)
        self.btnPrev.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/prev.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrev.setIcon(icon4)
        self.btnPrev.setObjectName(_fromUtf8("btnPrev"))
        self.horizontalLayout_6.addWidget(self.btnPrev)
        self.btnNext = QtGui.QPushButton(self.bbxExeEdit)
        self.btnNext.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNext.setIcon(icon5)
        self.btnNext.setObjectName(_fromUtf8("btnNext"))
        self.horizontalLayout_6.addWidget(self.btnNext)
        self.btnLast = QtGui.QPushButton(self.bbxExeEdit)
        self.btnLast.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLast.setIcon(icon6)
        self.btnLast.setObjectName(_fromUtf8("btnLast"))
        self.horizontalLayout_6.addWidget(self.btnLast)
        self.btnAdd = QtGui.QPushButton(self.bbxExeEdit)
        self.btnAdd.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAdd.setIcon(icon7)
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.horizontalLayout_6.addWidget(self.btnAdd)
        self.btnDel = QtGui.QPushButton(self.bbxExeEdit)
        self.btnDel.setText(_fromUtf8(""))
        self.btnDel.setIcon(icon2)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.horizontalLayout_6.addWidget(self.btnDel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btnCancel = QtGui.QPushButton(self.bbxExeEdit)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCancel.setIcon(icon8)
        self.btnCancel.setObjectName(_fromUtf8("btnCancel"))
        self.horizontalLayout_6.addWidget(self.btnCancel)
        self.btnOk = QtGui.QPushButton(self.bbxExeEdit)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/editedit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnOk.setIcon(icon9)
        self.btnOk.setObjectName(_fromUtf8("btnOk"))
        self.horizontalLayout_6.addWidget(self.btnOk)
        self.verticalLayout.addWidget(self.bbxExeEdit)
        self.lblNome.setBuddy(self.qleNome)
        self.lblDesc.setBuddy(self.qleDesc)
        self.lblGrlCena.setBuddy(self.cbxGrlCena)
        self.lblGrlIni.setBuddy(self.widGrlIni)
        self.lblGrlRnd.setBuddy(self.qsbGrlRnd)
        self.lblGrlAnvQtd.setBuddy(self.txtGrlAnvQtd)
        self.lblMetVntDir.setBuddy(self.qsbMetVntDir)
        self.lblMetVntVel.setBuddy(self.qsbMetVntVel)
        self.lblMetTto.setBuddy(self.qsbMetTeto)
        self.lblMetVis.setBuddy(self.qsbMetVisi)
        self.lblMetTmp.setBuddy(self.qsbMetTemp)
        self.lblMetPrs.setBuddy(self.qsbMetPres)

        self.retranslateUi(CDlgExeEditNEW)
        QtCore.QMetaObject.connectSlotsByName(CDlgExeEditNEW)

    def retranslateUi(self, CDlgExeEditNEW):
        CDlgExeEditNEW.setWindowTitle(_translate("CDlgExeEditNEW", "Edição de Exercícios", None))
        self.lblNome.setText(_translate("CDlgExeEditNEW", "&Sigla:", None))
        self.lblDesc.setText(_translate("CDlgExeEditNEW", "Descrição:", None))
        self.gbxGrl.setTitle(_translate("CDlgExeEditNEW", "Geral", None))
        self.lblGrlCena.setText(_translate("CDlgExeEditNEW", "Cenário:", None))
        self.lblGrlIni.setText(_translate("CDlgExeEditNEW", "Hora inicial:", None))
        self.lblGrlRnd.setText(_translate("CDlgExeEditNEW", "Aleatoriedade:", None))
        self.qsbGrlRnd.setSuffix(_translate("CDlgExeEditNEW", " %", None))
        self.lblGrlAnvQtd.setText(_translate("CDlgExeEditNEW", "Aeronaves:", None))
        self.txtGrlAnvQtd.setText(_translate("CDlgExeEditNEW", "0", None))
        self.gbxMet.setTitle(_translate("CDlgExeEditNEW", "Meteorologia", None))
        self.lblMetVnt.setText(_translate("CDlgExeEditNEW", "Vento", None))
        self.lblMetVntDir.setText(_translate("CDlgExeEditNEW", "Direção:", None))
        self.qsbMetVntDir.setSuffix(_translate("CDlgExeEditNEW", " gr", None))
        self.lblMetVntVel.setText(_translate("CDlgExeEditNEW", "Velocidade:", None))
        self.qsbMetVntVel.setSuffix(_translate("CDlgExeEditNEW", " kt", None))
        self.lblMetTto.setText(_translate("CDlgExeEditNEW", "Teto:", None))
        self.qsbMetTeto.setSuffix(_translate("CDlgExeEditNEW", " ft", None))
        self.lblMetVis.setText(_translate("CDlgExeEditNEW", "Visibilidade:", None))
        self.qsbMetVisi.setSuffix(_translate("CDlgExeEditNEW", " m", None))
        self.lblMetTmp.setText(_translate("CDlgExeEditNEW", "Temperatura:", None))
        self.qsbMetTemp.setSuffix(_translate("CDlgExeEditNEW", " gr", None))
        self.lblMetPrs.setText(_translate("CDlgExeEditNEW", "Pressão:", None))
        self.gbxAnv.setTitle(_translate("CDlgExeEditNEW", "Aeronaves", None))
        self.btnNew.setText(_translate("CDlgExeEditNEW", "Cria", None))
        self.btnEdit.setText(_translate("CDlgExeEditNEW", "Edita", None))
        self.btnRem.setText(_translate("CDlgExeEditNEW", "Remove", None))
        self.btnCancel.setText(_translate("CDlgExeEditNEW", "Cancela", None))
        self.btnOk.setText(_translate("CDlgExeEditNEW", "Ok", None))

import resources_rc
