# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_aer_data_new.ui'
#
# Created: Tue Jan 26 11:33:06 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DlgAerDataNEW(object):
    def setupUi(self, DlgAerDataNEW):
        DlgAerDataNEW.setObjectName(_fromUtf8("DlgAerDataNEW"))
        DlgAerDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        DlgAerDataNEW.resize(727, 625)
        DlgAerDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        DlgAerDataNEW.setSizeGripEnabled(True)
        DlgAerDataNEW.setModal(True)
        self.horizontalLayout = QtGui.QHBoxLayout(DlgAerDataNEW)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(DlgAerDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.wid_aer_tab = QtGui.QWidget(self.splitter)
        self.wid_aer_tab.setObjectName(_fromUtf8("wid_aer_tab"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.wid_aer_tab)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.qtw_aer_tab = QtGui.QTableWidget(self.wid_aer_tab)
        self.qtw_aer_tab.setObjectName(_fromUtf8("qtw_aer_tab"))
        self.qtw_aer_tab.setColumnCount(0)
        self.qtw_aer_tab.setRowCount(0)
        self.verticalLayout_7.addWidget(self.qtw_aer_tab)
        self.wid_aer_data = QtGui.QWidget(self.splitter)
        self.wid_aer_data.setObjectName(_fromUtf8("wid_aer_data"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wid_aer_data)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frm_aer_id = QtGui.QFrame(self.wid_aer_data)
        self.frm_aer_id.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_aer_id.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_aer_id.setLineWidth(1)
        self.frm_aer_id.setObjectName(_fromUtf8("frm_aer_id"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frm_aer_id)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbl_aer_id = QtGui.QLabel(self.frm_aer_id)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_aer_id.sizePolicy().hasHeightForWidth())
        self.lbl_aer_id.setSizePolicy(sizePolicy)
        self.lbl_aer_id.setObjectName(_fromUtf8("lbl_aer_id"))
        self.gridLayout_4.addWidget(self.lbl_aer_id, 0, 0, 1, 1)
        self.txt_aer_id = QtGui.QLabel(self.frm_aer_id)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_aer_id.setFont(font)
        self.txt_aer_id.setObjectName(_fromUtf8("txt_aer_id"))
        self.gridLayout_4.addWidget(self.txt_aer_id, 0, 1, 1, 1)
        self.lbl_aer_desc = QtGui.QLabel(self.frm_aer_id)
        self.lbl_aer_desc.setObjectName(_fromUtf8("lbl_aer_desc"))
        self.gridLayout_4.addWidget(self.lbl_aer_desc, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 2, 1, 1)
        self.qle_aer_desc = QtGui.QLineEdit(self.frm_aer_id)
        self.qle_aer_desc.setObjectName(_fromUtf8("qle_aer_desc"))
        self.gridLayout_4.addWidget(self.qle_aer_desc, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.frm_aer_id)
        self.tab_aer = QtGui.QTabWidget(self.wid_aer_data)
        self.tab_aer.setObjectName(_fromUtf8("tab_aer"))
        self.pag_aer = QtGui.QWidget()
        self.pag_aer.setObjectName(_fromUtf8("pag_aer"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pag_aer)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gbx_aer_dim = QtGui.QGroupBox(self.pag_aer)
        self.gbx_aer_dim.setObjectName(_fromUtf8("gbx_aer_dim"))
        self.gridLayout = QtGui.QGridLayout(self.gbx_aer_dim)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_comp = QtGui.QLabel(self.gbx_aer_dim)
        self.lbl_comp.setObjectName(_fromUtf8("lbl_comp"))
        self.gridLayout.addWidget(self.lbl_comp, 1, 0, 1, 1)
        self.lbl_larg = QtGui.QLabel(self.gbx_aer_dim)
        self.lbl_larg.setObjectName(_fromUtf8("lbl_larg"))
        self.gridLayout.addWidget(self.lbl_larg, 3, 0, 1, 1)
        self.sbx_comp = QtGui.QSpinBox(self.gbx_aer_dim)
        self.sbx_comp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_comp.setMaximum(5000)
        self.sbx_comp.setSingleStep(100)
        self.sbx_comp.setObjectName(_fromUtf8("sbx_comp"))
        self.gridLayout.addWidget(self.sbx_comp, 1, 1, 1, 1)
        self.sbx_larg = QtGui.QSpinBox(self.gbx_aer_dim)
        self.sbx_larg.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_larg.setMaximum(100)
        self.sbx_larg.setSingleStep(10)
        self.sbx_larg.setObjectName(_fromUtf8("sbx_larg"))
        self.gridLayout.addWidget(self.sbx_larg, 3, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.gbx_aer_dim)
        self.gbx_aer_pos = QtGui.QGroupBox(self.pag_aer)
        self.gbx_aer_pos.setObjectName(_fromUtf8("gbx_aer_pos"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbx_aer_pos)
        self.horizontalLayout_4.setMargin(3)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.cbx_tcrd = QtGui.QComboBox(self.gbx_aer_pos)
        self.cbx_tcrd.setMinimumSize(QtCore.QSize(150, 0))
        self.cbx_tcrd.setObjectName(_fromUtf8("cbx_tcrd"))
        self.horizontalLayout_4.addWidget(self.cbx_tcrd)
        self.stk_crd = QtGui.QStackedWidget(self.gbx_aer_pos)
        self.stk_crd.setObjectName(_fromUtf8("stk_crd"))
        self.crd_cart = QtGui.QWidget()
        self.crd_cart.setObjectName(_fromUtf8("crd_cart"))
        self.gridLayout_7 = QtGui.QGridLayout(self.crd_cart)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.dsb_cart_y = QtGui.QDoubleSpinBox(self.crd_cart)
        self.dsb_cart_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_cart_y.setDecimals(0)
        self.dsb_cart_y.setMinimum(-50000.0)
        self.dsb_cart_y.setMaximum(50000.0)
        self.dsb_cart_y.setSingleStep(100.0)
        self.dsb_cart_y.setObjectName(_fromUtf8("dsb_cart_y"))
        self.gridLayout_7.addWidget(self.dsb_cart_y, 2, 2, 1, 1)
        self.lbl_cart_y = QtGui.QLabel(self.crd_cart)
        self.lbl_cart_y.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cart_y.setObjectName(_fromUtf8("lbl_cart_y"))
        self.gridLayout_7.addWidget(self.lbl_cart_y, 2, 1, 1, 1)
        self.lbl_cart_x = QtGui.QLabel(self.crd_cart)
        self.lbl_cart_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cart_x.setObjectName(_fromUtf8("lbl_cart_x"))
        self.gridLayout_7.addWidget(self.lbl_cart_x, 1, 1, 1, 1)
        self.dsb_cart_x = QtGui.QDoubleSpinBox(self.crd_cart)
        self.dsb_cart_x.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_cart_x.setDecimals(0)
        self.dsb_cart_x.setMinimum(-50000.0)
        self.dsb_cart_x.setMaximum(50000.0)
        self.dsb_cart_x.setSingleStep(100.0)
        self.dsb_cart_x.setObjectName(_fromUtf8("dsb_cart_x"))
        self.gridLayout_7.addWidget(self.dsb_cart_x, 1, 2, 1, 1)
        self.lbl_cart_z = QtGui.QLabel(self.crd_cart)
        self.lbl_cart_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_cart_z.setObjectName(_fromUtf8("lbl_cart_z"))
        self.gridLayout_7.addWidget(self.lbl_cart_z, 3, 1, 1, 1)
        self.dsb_cart_z = QtGui.QDoubleSpinBox(self.crd_cart)
        self.dsb_cart_z.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_cart_z.setDecimals(0)
        self.dsb_cart_z.setMinimum(0.0)
        self.dsb_cart_z.setMaximum(80000.0)
        self.dsb_cart_z.setSingleStep(100.0)
        self.dsb_cart_z.setObjectName(_fromUtf8("dsb_cart_z"))
        self.gridLayout_7.addWidget(self.dsb_cart_z, 3, 2, 1, 1)
        self.stk_crd.addWidget(self.crd_cart)
        self.crd_pfix = QtGui.QWidget()
        self.crd_pfix.setObjectName(_fromUtf8("crd_pfix"))
        self.gridLayout_8 = QtGui.QGridLayout(self.crd_pfix)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lbl_pfix_dist = QtGui.QLabel(self.crd_pfix)
        self.lbl_pfix_dist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pfix_dist.setObjectName(_fromUtf8("lbl_pfix_dist"))
        self.gridLayout_8.addWidget(self.lbl_pfix_dist, 0, 0, 1, 1)
        self.sbx_pfix_dist = QtGui.QSpinBox(self.crd_pfix)
        self.sbx_pfix_dist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_pfix_dist.setMaximum(50000)
        self.sbx_pfix_dist.setSingleStep(100)
        self.sbx_pfix_dist.setObjectName(_fromUtf8("sbx_pfix_dist"))
        self.gridLayout_8.addWidget(self.sbx_pfix_dist, 0, 1, 1, 1)
        self.lbl_pfix_azim = QtGui.QLabel(self.crd_pfix)
        self.lbl_pfix_azim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pfix_azim.setObjectName(_fromUtf8("lbl_pfix_azim"))
        self.gridLayout_8.addWidget(self.lbl_pfix_azim, 1, 0, 1, 1)
        self.sbx_pfix_azim = QtGui.QSpinBox(self.crd_pfix)
        self.sbx_pfix_azim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_pfix_azim.setMaximum(360)
        self.sbx_pfix_azim.setSingleStep(3)
        self.sbx_pfix_azim.setObjectName(_fromUtf8("sbx_pfix_azim"))
        self.gridLayout_8.addWidget(self.sbx_pfix_azim, 1, 1, 1, 1)
        self.lbl_pfix_fixo = QtGui.QLabel(self.crd_pfix)
        self.lbl_pfix_fixo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pfix_fixo.setObjectName(_fromUtf8("lbl_pfix_fixo"))
        self.gridLayout_8.addWidget(self.lbl_pfix_fixo, 2, 0, 1, 1)
        self.cbx_pfix_fixo = QtGui.QComboBox(self.crd_pfix)
        self.cbx_pfix_fixo.setObjectName(_fromUtf8("cbx_pfix_fixo"))
        self.gridLayout_8.addWidget(self.cbx_pfix_fixo, 2, 1, 1, 1)
        self.stk_crd.addWidget(self.crd_pfix)
        self.crd_geo = QtGui.QWidget()
        self.crd_geo.setObjectName(_fromUtf8("crd_geo"))
        self.gridLayout_9 = QtGui.QGridLayout(self.crd_geo)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lbl_geo_lat = QtGui.QLabel(self.crd_geo)
        self.lbl_geo_lat.setMinimumSize(QtCore.QSize(140, 0))
        self.lbl_geo_lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_geo_lat.setObjectName(_fromUtf8("lbl_geo_lat"))
        self.gridLayout_9.addWidget(self.lbl_geo_lat, 0, 0, 1, 1)
        self.qle_geo_lat = QtGui.QLineEdit(self.crd_geo)
        self.qle_geo_lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qle_geo_lat.setObjectName(_fromUtf8("qle_geo_lat"))
        self.gridLayout_9.addWidget(self.qle_geo_lat, 0, 1, 1, 1)
        self.lbl_geo_lng = QtGui.QLabel(self.crd_geo)
        self.lbl_geo_lng.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_geo_lng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_geo_lng.setObjectName(_fromUtf8("lbl_geo_lng"))
        self.gridLayout_9.addWidget(self.lbl_geo_lng, 1, 0, 1, 1)
        self.qle_geo_lng = QtGui.QLineEdit(self.crd_geo)
        self.qle_geo_lng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qle_geo_lng.setObjectName(_fromUtf8("qle_geo_lng"))
        self.gridLayout_9.addWidget(self.qle_geo_lng, 1, 1, 1, 1)
        self.lbl_geo_alt = QtGui.QLabel(self.crd_geo)
        self.lbl_geo_alt.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_geo_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_geo_alt.setObjectName(_fromUtf8("lbl_geo_alt"))
        self.gridLayout_9.addWidget(self.lbl_geo_alt, 2, 0, 1, 1)
        self.sbx_geo_alt = QtGui.QSpinBox(self.crd_geo)
        self.sbx_geo_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_geo_alt.setMaximum(80000)
        self.sbx_geo_alt.setSingleStep(100)
        self.sbx_geo_alt.setObjectName(_fromUtf8("sbx_geo_alt"))
        self.gridLayout_9.addWidget(self.sbx_geo_alt, 2, 1, 1, 1)
        self.stk_crd.addWidget(self.crd_geo)
        self.crd_pol = QtGui.QWidget()
        self.crd_pol.setObjectName(_fromUtf8("crd_pol"))
        self.gridLayout_10 = QtGui.QGridLayout(self.crd_pol)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.lbl_pol_dist = QtGui.QLabel(self.crd_pol)
        self.lbl_pol_dist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pol_dist.setObjectName(_fromUtf8("lbl_pol_dist"))
        self.gridLayout_10.addWidget(self.lbl_pol_dist, 0, 0, 1, 1)
        self.lbl_pol_azim = QtGui.QLabel(self.crd_pol)
        self.lbl_pol_azim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pol_azim.setObjectName(_fromUtf8("lbl_pol_azim"))
        self.gridLayout_10.addWidget(self.lbl_pol_azim, 1, 0, 1, 1)
        self.lbl_pol_alt = QtGui.QLabel(self.crd_pol)
        self.lbl_pol_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_pol_alt.setObjectName(_fromUtf8("lbl_pol_alt"))
        self.gridLayout_10.addWidget(self.lbl_pol_alt, 2, 0, 1, 1)
        self.sbx_pol_dist = QtGui.QSpinBox(self.crd_pol)
        self.sbx_pol_dist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_pol_dist.setMaximum(50000)
        self.sbx_pol_dist.setSingleStep(100)
        self.sbx_pol_dist.setObjectName(_fromUtf8("sbx_pol_dist"))
        self.gridLayout_10.addWidget(self.sbx_pol_dist, 0, 1, 1, 1)
        self.sbx_pol_azim = QtGui.QSpinBox(self.crd_pol)
        self.sbx_pol_azim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_pol_azim.setMaximum(360)
        self.sbx_pol_azim.setSingleStep(3)
        self.sbx_pol_azim.setObjectName(_fromUtf8("sbx_pol_azim"))
        self.gridLayout_10.addWidget(self.sbx_pol_azim, 1, 1, 1, 1)
        self.sbx_pol_alt = QtGui.QSpinBox(self.crd_pol)
        self.sbx_pol_alt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_pol_alt.setMaximum(80000)
        self.sbx_pol_alt.setSingleStep(100)
        self.sbx_pol_alt.setObjectName(_fromUtf8("sbx_pol_alt"))
        self.gridLayout_10.addWidget(self.sbx_pol_alt, 2, 1, 1, 1)
        self.stk_crd.addWidget(self.crd_pol)
        self.horizontalLayout_4.addWidget(self.stk_crd)
        self.verticalLayout_5.addWidget(self.gbx_aer_pos)
        self.gbx_aer_geo = QtGui.QGroupBox(self.pag_aer)
        self.gbx_aer_geo.setObjectName(_fromUtf8("gbx_aer_geo"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gbx_aer_geo)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lbl_elev = QtGui.QLabel(self.gbx_aer_geo)
        self.lbl_elev.setObjectName(_fromUtf8("lbl_elev"))
        self.gridLayout_2.addWidget(self.lbl_elev, 0, 0, 1, 1)
        self.lbl_decl = QtGui.QLabel(self.gbx_aer_geo)
        self.lbl_decl.setObjectName(_fromUtf8("lbl_decl"))
        self.gridLayout_2.addWidget(self.lbl_decl, 1, 0, 1, 1)
        self.sbx_elev = QtGui.QSpinBox(self.gbx_aer_geo)
        self.sbx_elev.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_elev.setMaximum(10000)
        self.sbx_elev.setSingleStep(100)
        self.sbx_elev.setObjectName(_fromUtf8("sbx_elev"))
        self.gridLayout_2.addWidget(self.sbx_elev, 0, 2, 1, 1)
        self.dsb_decl = QtGui.QDoubleSpinBox(self.gbx_aer_geo)
        self.dsb_decl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_decl.setDecimals(1)
        self.dsb_decl.setMinimum(-90.0)
        self.dsb_decl.setMaximum(90.0)
        self.dsb_decl.setObjectName(_fromUtf8("dsb_decl"))
        self.gridLayout_2.addWidget(self.dsb_decl, 1, 2, 1, 1)
        self.verticalLayout_5.addWidget(self.gbx_aer_geo)
        self.tab_aer.addTab(self.pag_aer, _fromUtf8(""))
        self.pag_pst = QtGui.QWidget()
        self.pag_pst.setObjectName(_fromUtf8("pag_pst"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.pag_pst)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.gbx_aer_pst = QtGui.QGroupBox(self.pag_pst)
        self.gbx_aer_pst.setObjectName(_fromUtf8("gbx_aer_pst"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.gbx_aer_pst)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.qtw_aer_pst = QtGui.QTableWidget(self.gbx_aer_pst)
        self.qtw_aer_pst.setObjectName(_fromUtf8("qtw_aer_pst"))
        self.qtw_aer_pst.setColumnCount(0)
        self.qtw_aer_pst.setRowCount(0)
        self.verticalLayout_11.addWidget(self.qtw_aer_pst)
        self.verticalLayout_10.addWidget(self.gbx_aer_pst)
        self.gbx_aer_cab = QtGui.QGroupBox(self.pag_pst)
        self.gbx_aer_cab.setObjectName(_fromUtf8("gbx_aer_cab"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.gbx_aer_cab)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.qtw_aer_cab = QtGui.QTableWidget(self.gbx_aer_cab)
        self.qtw_aer_cab.setObjectName(_fromUtf8("qtw_aer_cab"))
        self.qtw_aer_cab.setColumnCount(0)
        self.qtw_aer_cab.setRowCount(0)
        self.verticalLayout_12.addWidget(self.qtw_aer_cab)
        self.verticalLayout_10.addWidget(self.gbx_aer_cab)
        self.tab_aer.addTab(self.pag_pst, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tab_aer)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frm_aer_bbx = QtGui.QFrame(self.wid_aer_data)
        self.frm_aer_bbx.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_aer_bbx.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_aer_bbx.setObjectName(_fromUtf8("frm_aer_bbx"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frm_aer_bbx)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btn_new = QtGui.QPushButton(self.frm_aer_bbx)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new.setIcon(icon)
        self.btn_new.setObjectName(_fromUtf8("btn_new"))
        self.horizontalLayout_3.addWidget(self.btn_new)
        self.btn_del = QtGui.QPushButton(self.frm_aer_bbx)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del.setIcon(icon1)
        self.btn_del.setObjectName(_fromUtf8("btn_del"))
        self.horizontalLayout_3.addWidget(self.btn_del)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.bbx_aer_tab = QtGui.QDialogButtonBox(self.frm_aer_bbx)
        self.bbx_aer_tab.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbx_aer_tab.setObjectName(_fromUtf8("bbx_aer_tab"))
        self.horizontalLayout_3.addWidget(self.bbx_aer_tab)
        self.verticalLayout_2.addWidget(self.frm_aer_bbx)
        self.horizontalLayout.addWidget(self.splitter)
        self.lbl_cart_y.setBuddy(self.dsb_cart_y)
        self.lbl_cart_x.setBuddy(self.dsb_cart_x)
        self.lbl_cart_z.setBuddy(self.dsb_cart_z)

        self.retranslateUi(DlgAerDataNEW)
        self.tab_aer.setCurrentIndex(0)
        self.stk_crd.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(DlgAerDataNEW)

    def retranslateUi(self, DlgAerDataNEW):
        DlgAerDataNEW.setWindowTitle(_translate("DlgAerDataNEW", "[ Edição de Aeródromos ]", None))
        self.lbl_aer_id.setText(_translate("DlgAerDataNEW", "Indicativo:", None))
        self.txt_aer_id.setText(_translate("DlgAerDataNEW", "TEST", None))
        self.lbl_aer_desc.setText(_translate("DlgAerDataNEW", "Descrição:", None))
        self.gbx_aer_dim.setTitle(_translate("DlgAerDataNEW", "Dimensão", None))
        self.lbl_comp.setText(_translate("DlgAerDataNEW", "Comprimento:", None))
        self.lbl_larg.setText(_translate("DlgAerDataNEW", "Largura:", None))
        self.sbx_comp.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.sbx_larg.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.gbx_aer_pos.setTitle(_translate("DlgAerDataNEW", "ARP", None))
        self.dsb_cart_y.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.lbl_cart_y.setText(_translate("DlgAerDataNEW", "Y:", None))
        self.lbl_cart_x.setText(_translate("DlgAerDataNEW", "X:", None))
        self.dsb_cart_x.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.lbl_cart_z.setText(_translate("DlgAerDataNEW", "Z:", None))
        self.dsb_cart_z.setSuffix(_translate("DlgAerDataNEW", " ft", None))
        self.lbl_pfix_dist.setText(_translate("DlgAerDataNEW", "Distância:", None))
        self.sbx_pfix_dist.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.lbl_pfix_azim.setText(_translate("DlgAerDataNEW", "Azimute:", None))
        self.sbx_pfix_azim.setSuffix(_translate("DlgAerDataNEW", " °", None))
        self.lbl_pfix_fixo.setText(_translate("DlgAerDataNEW", "Fixo:", None))
        self.lbl_geo_lat.setText(_translate("DlgAerDataNEW", "Latitude:", None))
        self.lbl_geo_lng.setText(_translate("DlgAerDataNEW", "Longitude:", None))
        self.lbl_geo_alt.setText(_translate("DlgAerDataNEW", "Altitude:", None))
        self.sbx_geo_alt.setSuffix(_translate("DlgAerDataNEW", " ft", None))
        self.lbl_pol_dist.setText(_translate("DlgAerDataNEW", "Distância:", None))
        self.lbl_pol_azim.setText(_translate("DlgAerDataNEW", "Azimute:", None))
        self.lbl_pol_alt.setText(_translate("DlgAerDataNEW", "Altitude:", None))
        self.sbx_pol_dist.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.sbx_pol_azim.setSuffix(_translate("DlgAerDataNEW", " °", None))
        self.sbx_pol_alt.setSuffix(_translate("DlgAerDataNEW", " ft", None))
        self.gbx_aer_geo.setTitle(_translate("DlgAerDataNEW", "Geografia", None))
        self.lbl_elev.setText(_translate("DlgAerDataNEW", "Elevação:", None))
        self.lbl_decl.setText(_translate("DlgAerDataNEW", "Declinação:", None))
        self.sbx_elev.setSuffix(_translate("DlgAerDataNEW", " m", None))
        self.dsb_decl.setSuffix(_translate("DlgAerDataNEW", " gr", None))
        self.tab_aer.setTabText(self.tab_aer.indexOf(self.pag_aer), _translate("DlgAerDataNEW", "Aeródromo", None))
        self.gbx_aer_pst.setTitle(_translate("DlgAerDataNEW", "Pistas", None))
        self.gbx_aer_cab.setTitle(_translate("DlgAerDataNEW", "Cabeceiras", None))
        self.tab_aer.setTabText(self.tab_aer.indexOf(self.pag_pst), _translate("DlgAerDataNEW", "Pistas", None))
        self.btn_new.setText(_translate("DlgAerDataNEW", "Novo", None))
        self.btn_del.setText(_translate("DlgAerDataNEW", "Remove", None))

import qrc_resources_rc
