# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_fix_data_new.ui'
#
# Created: Tue Jan 26 11:33:06 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgFixDataNEW(object):
    def setupUi(self, dlgFixDataNEW):
        dlgFixDataNEW.setObjectName(_fromUtf8("dlgFixDataNEW"))
        dlgFixDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        dlgFixDataNEW.resize(737, 474)
        dlgFixDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        dlgFixDataNEW.setSizeGripEnabled(True)
        dlgFixDataNEW.setModal(True)
        self.horizontalLayout_6 = QtGui.QHBoxLayout(dlgFixDataNEW)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.splitter = QtGui.QSplitter(dlgFixDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.widFixTab = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widFixTab.sizePolicy().hasHeightForWidth())
        self.widFixTab.setSizePolicy(sizePolicy)
        self.widFixTab.setObjectName(_fromUtf8("widFixTab"))
        self.verticalLayout = QtGui.QVBoxLayout(self.widFixTab)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qtwFixTab = QtGui.QTableWidget(self.widFixTab)
        self.qtwFixTab.setObjectName(_fromUtf8("qtwFixTab"))
        self.qtwFixTab.setColumnCount(0)
        self.qtwFixTab.setRowCount(0)
        self.verticalLayout.addWidget(self.qtwFixTab)
        self.widFixDat = QtGui.QWidget(self.splitter)
        self.widFixDat.setObjectName(_fromUtf8("widFixDat"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widFixDat)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frmFixID = QtGui.QFrame(self.widFixDat)
        self.frmFixID.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmFixID.setFrameShadow(QtGui.QFrame.Raised)
        self.frmFixID.setObjectName(_fromUtf8("frmFixID"))
        self.gridLayout = QtGui.QGridLayout(self.frmFixID)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 4, 1, 1)
        self.txtFixID = QtGui.QLabel(self.frmFixID)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtFixID.setFont(font)
        self.txtFixID.setObjectName(_fromUtf8("txtFixID"))
        self.gridLayout.addWidget(self.txtFixID, 0, 3, 1, 1)
        self.lblFixDesc = QtGui.QLabel(self.frmFixID)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblFixDesc.sizePolicy().hasHeightForWidth())
        self.lblFixDesc.setSizePolicy(sizePolicy)
        self.lblFixDesc.setObjectName(_fromUtf8("lblFixDesc"))
        self.gridLayout.addWidget(self.lblFixDesc, 2, 1, 1, 1)
        self.lblFixID = QtGui.QLabel(self.frmFixID)
        self.lblFixID.setObjectName(_fromUtf8("lblFixID"))
        self.gridLayout.addWidget(self.lblFixID, 0, 1, 1, 1)
        self.qleFixDesc = QtGui.QLineEdit(self.frmFixID)
        self.qleFixDesc.setObjectName(_fromUtf8("qleFixDesc"))
        self.gridLayout.addWidget(self.qleFixDesc, 2, 3, 1, 2)
        self.verticalLayout_2.addWidget(self.frmFixID)
        self.gbxFixAids = QtGui.QGroupBox(self.widFixDat)
        self.gbxFixAids.setObjectName(_fromUtf8("gbxFixAids"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gbxFixAids)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.ckxVOR = QtGui.QCheckBox(self.gbxFixAids)
        self.ckxVOR.setObjectName(_fromUtf8("ckxVOR"))
        self.horizontalLayout.addWidget(self.ckxVOR)
        self.ckxNDB = QtGui.QCheckBox(self.gbxFixAids)
        self.ckxNDB.setObjectName(_fromUtf8("ckxNDB"))
        self.horizontalLayout.addWidget(self.ckxNDB)
        self.ckxDME = QtGui.QCheckBox(self.gbxFixAids)
        self.ckxDME.setObjectName(_fromUtf8("ckxDME"))
        self.horizontalLayout.addWidget(self.ckxDME)
        self.verticalLayout_2.addWidget(self.gbxFixAids)
        self.gbxFixFreq = QtGui.QGroupBox(self.widFixDat)
        self.gbxFixFreq.setObjectName(_fromUtf8("gbxFixFreq"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.gbxFixFreq)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.lblFreq = QtGui.QLabel(self.gbxFixFreq)
        self.lblFreq.setObjectName(_fromUtf8("lblFreq"))
        self.horizontalLayout_4.addWidget(self.lblFreq)
        self.dsbFreq = QtGui.QDoubleSpinBox(self.gbxFixFreq)
        self.dsbFreq.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbFreq.setDecimals(1)
        self.dsbFreq.setMaximum(100000.0)
        self.dsbFreq.setSingleStep(1000.0)
        self.dsbFreq.setObjectName(_fromUtf8("dsbFreq"))
        self.horizontalLayout_4.addWidget(self.dsbFreq)
        self.verticalLayout_2.addWidget(self.gbxFixFreq)
        self.gbxFixPos = QtGui.QGroupBox(self.widFixDat)
        self.gbxFixPos.setObjectName(_fromUtf8("gbxFixPos"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.gbxFixPos)
        self.horizontalLayout_3.setMargin(3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cbxTCrd = QtGui.QComboBox(self.gbxFixPos)
        self.cbxTCrd.setMinimumSize(QtCore.QSize(150, 0))
        self.cbxTCrd.setObjectName(_fromUtf8("cbxTCrd"))
        self.horizontalLayout_3.addWidget(self.cbxTCrd)
        self.stkCrd = QtGui.QStackedWidget(self.gbxFixPos)
        self.stkCrd.setObjectName(_fromUtf8("stkCrd"))
        self.crdCart = QtGui.QWidget()
        self.crdCart.setObjectName(_fromUtf8("crdCart"))
        self.gridLayout_7 = QtGui.QGridLayout(self.crdCart)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.dsbCartY = QtGui.QDoubleSpinBox(self.crdCart)
        self.dsbCartY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCartY.setDecimals(0)
        self.dsbCartY.setMinimum(-50000.0)
        self.dsbCartY.setMaximum(50000.0)
        self.dsbCartY.setSingleStep(100.0)
        self.dsbCartY.setObjectName(_fromUtf8("dsbCartY"))
        self.gridLayout_7.addWidget(self.dsbCartY, 2, 2, 1, 1)
        self.lblCartY = QtGui.QLabel(self.crdCart)
        self.lblCartY.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCartY.setObjectName(_fromUtf8("lblCartY"))
        self.gridLayout_7.addWidget(self.lblCartY, 2, 1, 1, 1)
        self.lblCartX = QtGui.QLabel(self.crdCart)
        self.lblCartX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCartX.setObjectName(_fromUtf8("lblCartX"))
        self.gridLayout_7.addWidget(self.lblCartX, 1, 1, 1, 1)
        self.dsbCartX = QtGui.QDoubleSpinBox(self.crdCart)
        self.dsbCartX.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCartX.setDecimals(0)
        self.dsbCartX.setMinimum(-50000.0)
        self.dsbCartX.setMaximum(50000.0)
        self.dsbCartX.setSingleStep(100.0)
        self.dsbCartX.setObjectName(_fromUtf8("dsbCartX"))
        self.gridLayout_7.addWidget(self.dsbCartX, 1, 2, 1, 1)
        self.lblCartZ = QtGui.QLabel(self.crdCart)
        self.lblCartZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblCartZ.setObjectName(_fromUtf8("lblCartZ"))
        self.gridLayout_7.addWidget(self.lblCartZ, 3, 1, 1, 1)
        self.dsbCartZ = QtGui.QDoubleSpinBox(self.crdCart)
        self.dsbCartZ.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsbCartZ.setDecimals(0)
        self.dsbCartZ.setMinimum(0.0)
        self.dsbCartZ.setMaximum(80000.0)
        self.dsbCartZ.setSingleStep(100.0)
        self.dsbCartZ.setObjectName(_fromUtf8("dsbCartZ"))
        self.gridLayout_7.addWidget(self.dsbCartZ, 3, 2, 1, 1)
        self.stkCrd.addWidget(self.crdCart)
        self.crdPFix = QtGui.QWidget()
        self.crdPFix.setObjectName(_fromUtf8("crdPFix"))
        self.gridLayout_8 = QtGui.QGridLayout(self.crdPFix)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.lblPFixDist = QtGui.QLabel(self.crdPFix)
        self.lblPFixDist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPFixDist.setObjectName(_fromUtf8("lblPFixDist"))
        self.gridLayout_8.addWidget(self.lblPFixDist, 0, 0, 1, 1)
        self.sbxPFixDist = QtGui.QSpinBox(self.crdPFix)
        self.sbxPFixDist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxPFixDist.setMaximum(50000)
        self.sbxPFixDist.setSingleStep(100)
        self.sbxPFixDist.setObjectName(_fromUtf8("sbxPFixDist"))
        self.gridLayout_8.addWidget(self.sbxPFixDist, 0, 1, 1, 1)
        self.lblPFixAzim = QtGui.QLabel(self.crdPFix)
        self.lblPFixAzim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPFixAzim.setObjectName(_fromUtf8("lblPFixAzim"))
        self.gridLayout_8.addWidget(self.lblPFixAzim, 1, 0, 1, 1)
        self.sbxPFixAzim = QtGui.QSpinBox(self.crdPFix)
        self.sbxPFixAzim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxPFixAzim.setMaximum(360)
        self.sbxPFixAzim.setSingleStep(3)
        self.sbxPFixAzim.setObjectName(_fromUtf8("sbxPFixAzim"))
        self.gridLayout_8.addWidget(self.sbxPFixAzim, 1, 1, 1, 1)
        self.lblPFixFixo = QtGui.QLabel(self.crdPFix)
        self.lblPFixFixo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPFixFixo.setObjectName(_fromUtf8("lblPFixFixo"))
        self.gridLayout_8.addWidget(self.lblPFixFixo, 2, 0, 1, 1)
        self.cbxPFixFixo = QtGui.QComboBox(self.crdPFix)
        self.cbxPFixFixo.setObjectName(_fromUtf8("cbxPFixFixo"))
        self.gridLayout_8.addWidget(self.cbxPFixFixo, 2, 1, 1, 1)
        self.stkCrd.addWidget(self.crdPFix)
        self.crdGeo = QtGui.QWidget()
        self.crdGeo.setObjectName(_fromUtf8("crdGeo"))
        self.gridLayout_9 = QtGui.QGridLayout(self.crdGeo)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.lblGeoLat = QtGui.QLabel(self.crdGeo)
        self.lblGeoLat.setMinimumSize(QtCore.QSize(140, 0))
        self.lblGeoLat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGeoLat.setObjectName(_fromUtf8("lblGeoLat"))
        self.gridLayout_9.addWidget(self.lblGeoLat, 0, 0, 1, 1)
        self.qleGeoLat = QtGui.QLineEdit(self.crdGeo)
        self.qleGeoLat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleGeoLat.setObjectName(_fromUtf8("qleGeoLat"))
        self.gridLayout_9.addWidget(self.qleGeoLat, 0, 1, 1, 1)
        self.lblGeoLng = QtGui.QLabel(self.crdGeo)
        self.lblGeoLng.setMinimumSize(QtCore.QSize(0, 0))
        self.lblGeoLng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGeoLng.setObjectName(_fromUtf8("lblGeoLng"))
        self.gridLayout_9.addWidget(self.lblGeoLng, 1, 0, 1, 1)
        self.qleGeoLng = QtGui.QLineEdit(self.crdGeo)
        self.qleGeoLng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qleGeoLng.setObjectName(_fromUtf8("qleGeoLng"))
        self.gridLayout_9.addWidget(self.qleGeoLng, 1, 1, 1, 1)
        self.lblGeoAlt = QtGui.QLabel(self.crdGeo)
        self.lblGeoAlt.setMinimumSize(QtCore.QSize(0, 0))
        self.lblGeoAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGeoAlt.setObjectName(_fromUtf8("lblGeoAlt"))
        self.gridLayout_9.addWidget(self.lblGeoAlt, 2, 0, 1, 1)
        self.sbxGeoAlt = QtGui.QSpinBox(self.crdGeo)
        self.sbxGeoAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxGeoAlt.setMaximum(80000)
        self.sbxGeoAlt.setSingleStep(100)
        self.sbxGeoAlt.setObjectName(_fromUtf8("sbxGeoAlt"))
        self.gridLayout_9.addWidget(self.sbxGeoAlt, 2, 1, 1, 1)
        self.stkCrd.addWidget(self.crdGeo)
        self.crdPol = QtGui.QWidget()
        self.crdPol.setObjectName(_fromUtf8("crdPol"))
        self.gridLayout_10 = QtGui.QGridLayout(self.crdPol)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.lblPolDist = QtGui.QLabel(self.crdPol)
        self.lblPolDist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPolDist.setObjectName(_fromUtf8("lblPolDist"))
        self.gridLayout_10.addWidget(self.lblPolDist, 0, 0, 1, 1)
        self.lblPolAzim = QtGui.QLabel(self.crdPol)
        self.lblPolAzim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPolAzim.setObjectName(_fromUtf8("lblPolAzim"))
        self.gridLayout_10.addWidget(self.lblPolAzim, 1, 0, 1, 1)
        self.lblPolAlt = QtGui.QLabel(self.crdPol)
        self.lblPolAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPolAlt.setObjectName(_fromUtf8("lblPolAlt"))
        self.gridLayout_10.addWidget(self.lblPolAlt, 2, 0, 1, 1)
        self.sbxPolDist = QtGui.QSpinBox(self.crdPol)
        self.sbxPolDist.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxPolDist.setMaximum(50000)
        self.sbxPolDist.setSingleStep(100)
        self.sbxPolDist.setObjectName(_fromUtf8("sbxPolDist"))
        self.gridLayout_10.addWidget(self.sbxPolDist, 0, 1, 1, 1)
        self.sbxPolAzim = QtGui.QSpinBox(self.crdPol)
        self.sbxPolAzim.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxPolAzim.setMaximum(360)
        self.sbxPolAzim.setSingleStep(3)
        self.sbxPolAzim.setObjectName(_fromUtf8("sbxPolAzim"))
        self.gridLayout_10.addWidget(self.sbxPolAzim, 1, 1, 1, 1)
        self.sbxPolAlt = QtGui.QSpinBox(self.crdPol)
        self.sbxPolAlt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbxPolAlt.setMaximum(80000)
        self.sbxPolAlt.setSingleStep(100)
        self.sbxPolAlt.setObjectName(_fromUtf8("sbxPolAlt"))
        self.gridLayout_10.addWidget(self.sbxPolAlt, 2, 1, 1, 1)
        self.stkCrd.addWidget(self.crdPol)
        self.horizontalLayout_3.addWidget(self.stkCrd)
        self.verticalLayout_2.addWidget(self.gbxFixPos)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.frmFixBBX = QtGui.QFrame(self.widFixDat)
        self.frmFixBBX.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frmFixBBX.setFrameShadow(QtGui.QFrame.Raised)
        self.frmFixBBX.setObjectName(_fromUtf8("frmFixBBX"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frmFixBBX)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnNew = QtGui.QPushButton(self.frmFixBBX)
        self.btnNew.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.horizontalLayout_2.addWidget(self.btnNew)
        self.btnDel = QtGui.QPushButton(self.frmFixBBX)
        self.btnDel.setFocusPolicy(QtCore.Qt.NoFocus)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDel.setIcon(icon1)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.horizontalLayout_2.addWidget(self.btnDel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.bbxFixTab = QtGui.QDialogButtonBox(self.frmFixBBX)
        self.bbxFixTab.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.bbxFixTab.setObjectName(_fromUtf8("bbxFixTab"))
        self.horizontalLayout_2.addWidget(self.bbxFixTab)
        self.verticalLayout_2.addWidget(self.frmFixBBX)
        self.horizontalLayout_6.addWidget(self.splitter)
        self.lblCartY.setBuddy(self.dsbCartY)
        self.lblCartX.setBuddy(self.dsbCartX)
        self.lblCartZ.setBuddy(self.dsbCartZ)

        self.retranslateUi(dlgFixDataNEW)
        self.stkCrd.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(dlgFixDataNEW)
        dlgFixDataNEW.setTabOrder(self.ckxVOR, self.ckxNDB)
        dlgFixDataNEW.setTabOrder(self.ckxNDB, self.ckxDME)

    def retranslateUi(self, dlgFixDataNEW):
        dlgFixDataNEW.setWindowTitle(_translate("dlgFixDataNEW", "TrackS [ Edição de Fixos ]", None))
        self.txtFixID.setText(_translate("dlgFixDataNEW", "Nonono", None))
        self.lblFixDesc.setText(_translate("dlgFixDataNEW", "Descrição:", None))
        self.lblFixID.setText(_translate("dlgFixDataNEW", "Indicativo:", None))
        self.gbxFixAids.setTitle(_translate("dlgFixDataNEW", "Navaids", None))
        self.ckxVOR.setText(_translate("dlgFixDataNEW", "VOR", None))
        self.ckxNDB.setText(_translate("dlgFixDataNEW", "NDB", None))
        self.ckxDME.setText(_translate("dlgFixDataNEW", "DME", None))
        self.gbxFixFreq.setTitle(_translate("dlgFixDataNEW", "Freqüência", None))
        self.lblFreq.setText(_translate("dlgFixDataNEW", "Freqüência:", None))
        self.dsbFreq.setSuffix(_translate("dlgFixDataNEW", " Hz", None))
        self.gbxFixPos.setTitle(_translate("dlgFixDataNEW", "Posicão", None))
        self.dsbCartY.setSuffix(_translate("dlgFixDataNEW", " m", None))
        self.lblCartY.setText(_translate("dlgFixDataNEW", "Y:", None))
        self.lblCartX.setText(_translate("dlgFixDataNEW", "X:", None))
        self.dsbCartX.setSuffix(_translate("dlgFixDataNEW", " m", None))
        self.lblCartZ.setText(_translate("dlgFixDataNEW", "Z:", None))
        self.dsbCartZ.setSuffix(_translate("dlgFixDataNEW", " ft", None))
        self.lblPFixDist.setText(_translate("dlgFixDataNEW", "Distância:", None))
        self.sbxPFixDist.setSuffix(_translate("dlgFixDataNEW", " m", None))
        self.lblPFixAzim.setText(_translate("dlgFixDataNEW", "Azimute:", None))
        self.sbxPFixAzim.setSuffix(_translate("dlgFixDataNEW", " °", None))
        self.lblPFixFixo.setText(_translate("dlgFixDataNEW", "Fixo:", None))
        self.lblGeoLat.setText(_translate("dlgFixDataNEW", "Latitude:", None))
        self.lblGeoLng.setText(_translate("dlgFixDataNEW", "Longitude:", None))
        self.lblGeoAlt.setText(_translate("dlgFixDataNEW", "Altitude:", None))
        self.sbxGeoAlt.setSuffix(_translate("dlgFixDataNEW", " ft", None))
        self.lblPolDist.setText(_translate("dlgFixDataNEW", "Distância:", None))
        self.lblPolAzim.setText(_translate("dlgFixDataNEW", "Azimute:", None))
        self.lblPolAlt.setText(_translate("dlgFixDataNEW", "Altitude:", None))
        self.sbxPolDist.setSuffix(_translate("dlgFixDataNEW", " m", None))
        self.sbxPolAzim.setSuffix(_translate("dlgFixDataNEW", " °", None))
        self.sbxPolAlt.setSuffix(_translate("dlgFixDataNEW", " ft", None))
        self.btnNew.setText(_translate("dlgFixDataNEW", "Novo", None))
        self.btnDel.setText(_translate("dlgFixDataNEW", "Remove", None))

import qrc_resources_rc
