# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './dlg_aer_data_new.ui'
#
# Created: Wed Dec  7 14:50:51 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_CDlgAerDataNEW(object):
    def setupUi(self, CDlgAerDataNEW):
        CDlgAerDataNEW.setObjectName(_fromUtf8("CDlgAerDataNEW"))
        CDlgAerDataNEW.setWindowModality(QtCore.Qt.WindowModal)
        CDlgAerDataNEW.resize(769, 608)
        CDlgAerDataNEW.setLocale(QtCore.QLocale(QtCore.QLocale.Portuguese, QtCore.QLocale.Brazil))
        CDlgAerDataNEW.setSizeGripEnabled(True)
        CDlgAerDataNEW.setModal(True)
        self.horizontalLayout = QtGui.QHBoxLayout(CDlgAerDataNEW)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(CDlgAerDataNEW)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.wid_qwt = QtGui.QWidget(self.splitter)
        self.wid_qwt.setObjectName(_fromUtf8("wid_qwt"))
        self.verticalLayout = QtGui.QVBoxLayout(self.wid_qwt)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.qtw_aer = QtGui.QTableWidget(self.wid_qwt)
        self.qtw_aer.setObjectName(_fromUtf8("qtw_aer"))
        self.qtw_aer.setColumnCount(0)
        self.qtw_aer.setRowCount(0)
        self.verticalLayout.addWidget(self.qtw_aer)
        self.frm_dbb_aer = QtGui.QFrame(self.wid_qwt)
        self.frm_dbb_aer.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_dbb_aer.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_dbb_aer.setObjectName(_fromUtf8("frm_dbb_aer"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frm_dbb_aer)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btn_new_aer = QtGui.QPushButton(self.frm_dbb_aer)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new_aer.setIcon(icon)
        self.btn_new_aer.setObjectName(_fromUtf8("btn_new_aer"))
        self.horizontalLayout_4.addWidget(self.btn_new_aer)
        self.btn_del_aer = QtGui.QPushButton(self.frm_dbb_aer)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/dbedit/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_del_aer.setIcon(icon1)
        self.btn_del_aer.setObjectName(_fromUtf8("btn_del_aer"))
        self.horizontalLayout_4.addWidget(self.btn_del_aer)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.dbb_aer = QtGui.QDialogButtonBox(self.frm_dbb_aer)
        self.dbb_aer.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.dbb_aer.setObjectName(_fromUtf8("dbb_aer"))
        self.horizontalLayout_4.addWidget(self.dbb_aer)
        self.verticalLayout.addWidget(self.frm_dbb_aer)
        self.wid_data = QtGui.QWidget(self.splitter)
        self.wid_data.setObjectName(_fromUtf8("wid_data"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wid_data)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frm_id = QtGui.QFrame(self.wid_data)
        self.frm_id.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_id.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_id.setLineWidth(1)
        self.frm_id.setObjectName(_fromUtf8("frm_id"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frm_id)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.lbl_indc = QtGui.QLabel(self.frm_id)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_indc.sizePolicy().hasHeightForWidth())
        self.lbl_indc.setSizePolicy(sizePolicy)
        self.lbl_indc.setObjectName(_fromUtf8("lbl_indc"))
        self.gridLayout_4.addWidget(self.lbl_indc, 0, 0, 1, 1)
        self.txt_indc = QtGui.QLabel(self.frm_id)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt_indc.setFont(font)
        self.txt_indc.setObjectName(_fromUtf8("txt_indc"))
        self.gridLayout_4.addWidget(self.txt_indc, 0, 1, 1, 1)
        self.lbl_desc = QtGui.QLabel(self.frm_id)
        self.lbl_desc.setObjectName(_fromUtf8("lbl_desc"))
        self.gridLayout_4.addWidget(self.lbl_desc, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.qle_desc = QtGui.QLineEdit(self.frm_id)
        self.qle_desc.setObjectName(_fromUtf8("qle_desc"))
        self.gridLayout_4.addWidget(self.qle_desc, 1, 1, 1, 2)
        self.verticalLayout_2.addWidget(self.frm_id)
        self.gbx_arp = QtGui.QGroupBox(self.wid_data)
        self.gbx_arp.setObjectName(_fromUtf8("gbx_arp"))
        self.gridLayout = QtGui.QGridLayout(self.gbx_arp)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lbl_elev = QtGui.QLabel(self.gbx_arp)
        self.lbl_elev.setObjectName(_fromUtf8("lbl_elev"))
        self.gridLayout.addWidget(self.lbl_elev, 2, 0, 1, 1)
        self.lbl_lat = QtGui.QLabel(self.gbx_arp)
        self.lbl_lat.setMinimumSize(QtCore.QSize(140, 0))
        self.lbl_lat.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lat.setObjectName(_fromUtf8("lbl_lat"))
        self.gridLayout.addWidget(self.lbl_lat, 0, 0, 1, 1)
        self.lbl_lng = QtGui.QLabel(self.gbx_arp)
        self.lbl_lng.setMinimumSize(QtCore.QSize(0, 0))
        self.lbl_lng.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lbl_lng.setObjectName(_fromUtf8("lbl_lng"))
        self.gridLayout.addWidget(self.lbl_lng, 1, 0, 1, 1)
        self.qle_lat = QtGui.QLineEdit(self.gbx_arp)
        self.qle_lat.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qle_lat.setObjectName(_fromUtf8("qle_lat"))
        self.gridLayout.addWidget(self.qle_lat, 0, 1, 1, 1)
        self.sbx_elev = QtGui.QSpinBox(self.gbx_arp)
        self.sbx_elev.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sbx_elev.setMaximum(5000)
        self.sbx_elev.setSingleStep(100)
        self.sbx_elev.setObjectName(_fromUtf8("sbx_elev"))
        self.gridLayout.addWidget(self.sbx_elev, 2, 1, 1, 1)
        self.lbl_decl = QtGui.QLabel(self.gbx_arp)
        self.lbl_decl.setObjectName(_fromUtf8("lbl_decl"))
        self.gridLayout.addWidget(self.lbl_decl, 3, 0, 1, 1)
        self.dsb_decl = QtGui.QDoubleSpinBox(self.gbx_arp)
        self.dsb_decl.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.dsb_decl.setDecimals(1)
        self.dsb_decl.setMinimum(-90.0)
        self.dsb_decl.setMaximum(90.0)
        self.dsb_decl.setObjectName(_fromUtf8("dsb_decl"))
        self.gridLayout.addWidget(self.dsb_decl, 3, 1, 1, 1)
        self.qle_lng = QtGui.QLineEdit(self.gbx_arp)
        self.qle_lng.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.qle_lng.setObjectName(_fromUtf8("qle_lng"))
        self.gridLayout.addWidget(self.qle_lng, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.gbx_arp)
        self.gbx_pst = QtGui.QGroupBox(self.wid_data)
        self.gbx_pst.setObjectName(_fromUtf8("gbx_pst"))
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.gbx_pst)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.qtw_pst = QtGui.QTableWidget(self.gbx_pst)
        self.qtw_pst.setObjectName(_fromUtf8("qtw_pst"))
        self.qtw_pst.setColumnCount(0)
        self.qtw_pst.setRowCount(0)
        self.verticalLayout_11.addWidget(self.qtw_pst)
        self.verticalLayout_2.addWidget(self.gbx_pst)
        self.frm_bbx_pst = QtGui.QFrame(self.wid_data)
        self.frm_bbx_pst.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frm_bbx_pst.setFrameShadow(QtGui.QFrame.Raised)
        self.frm_bbx_pst.setObjectName(_fromUtf8("frm_bbx_pst"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frm_bbx_pst)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.btn_new_pst = QtGui.QPushButton(self.frm_bbx_pst)
        self.btn_new_pst.setIcon(icon)
        self.btn_new_pst.setObjectName(_fromUtf8("btn_new_pst"))
        self.horizontalLayout_3.addWidget(self.btn_new_pst)
        self.btn_del_pst = QtGui.QPushButton(self.frm_bbx_pst)
        self.btn_del_pst.setIcon(icon1)
        self.btn_del_pst.setObjectName(_fromUtf8("btn_del_pst"))
        self.horizontalLayout_3.addWidget(self.btn_del_pst)
        self.verticalLayout_2.addWidget(self.frm_bbx_pst)
        self.horizontalLayout.addWidget(self.splitter)

        self.retranslateUi(CDlgAerDataNEW)
        QtCore.QMetaObject.connectSlotsByName(CDlgAerDataNEW)

    def retranslateUi(self, CDlgAerDataNEW):
        CDlgAerDataNEW.setWindowTitle(_translate("CDlgAerDataNEW", "Edição de Aeródromos", None))
        self.btn_new_aer.setText(_translate("CDlgAerDataNEW", "Novo", None))
        self.btn_del_aer.setText(_translate("CDlgAerDataNEW", "Remove", None))
        self.lbl_indc.setText(_translate("CDlgAerDataNEW", "Indicativo:", None))
        self.txt_indc.setText(_translate("CDlgAerDataNEW", "STST", None))
        self.lbl_desc.setText(_translate("CDlgAerDataNEW", "Descrição:", None))
        self.qle_desc.setText(_translate("CDlgAerDataNEW", "Teste", None))
        self.gbx_arp.setTitle(_translate("CDlgAerDataNEW", "ARP", None))
        self.lbl_elev.setText(_translate("CDlgAerDataNEW", "Elevação:", None))
        self.lbl_lat.setText(_translate("CDlgAerDataNEW", "Latitude:", None))
        self.lbl_lng.setText(_translate("CDlgAerDataNEW", "Longitude:", None))
        self.qle_lat.setText(_translate("CDlgAerDataNEW", "1961.19S", None))
        self.sbx_elev.setSuffix(_translate("CDlgAerDataNEW", " m", None))
        self.lbl_decl.setText(_translate("CDlgAerDataNEW", "Declinação Magnética:", None))
        self.dsb_decl.setSuffix(_translate("CDlgAerDataNEW", " gr", None))
        self.qle_lng.setText(_translate("CDlgAerDataNEW", "1970.02W", None))
        self.gbx_pst.setTitle(_translate("CDlgAerDataNEW", "Pistas", None))
        self.btn_new_pst.setText(_translate("CDlgAerDataNEW", "Novo", None))
        self.btn_del_pst.setText(_translate("CDlgAerDataNEW", "Remove", None))

import resources_rc
